package org.schema;

import org.stjs.javascript.Date;
import org.cassproject.schema.general.EcRemoteLinkedData;

/**
 * Schema.org/Report
 * A Report generated by governmental or non-governmental organization.
 * @author schema.org
 * @class Report
 * @module org.schema
 * @extends Article
 */
public class Report extends Article
{
	/**
	 * Constructor, automatically sets @context and @type.
	 * @constructor
	 */
	public Report()
	{
		context="http://schema.org/";
		type="Report";
	}

	/**
	 * Schema.org/reportNumber
	 * The number or other unique designator assigned to a Report by the publishing organization.
	 * @property reportNumber
	 * @type Text
	 */
	public String reportNumber;

}