version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  target-branch: version/3.0
  ignore:
  - dependency-name: org.antlr:antlr4-maven-plugin
    versions:
    - 4.9.1
