/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:00 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class AggregatedElement extends EcRemoteLinkedData {

    protected Array<BreakdownElementIdentifier> beId;
    protected Array<BreakdownElementName> name;
    protected BreakdownElementEssentiality esc;
    protected AggregatedElementType beType;
    protected Array<AggregatedElementRevision> beRev;
    protected s3000l.OperationalTask.Secs secs;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public Array<BreakdownElementIdentifier> getBeId() {
        if (beId == null) {
            beId = new Array<BreakdownElementIdentifier>();
        }
        return this.beId;
    }

    public Array<BreakdownElementName> getName() {
        if (name == null) {
            name = new Array<BreakdownElementName>();
        }
        return this.name;
    }

    public BreakdownElementEssentiality getEsc() {
        return esc;
    }

    public void setEsc(BreakdownElementEssentiality value) {
        this.esc = value;
    }

    public AggregatedElementType getBeType() {
        return beType;
    }

    public void setBeType(AggregatedElementType value) {
        this.beType = value;
    }

    public Array<AggregatedElementRevision> getBeRev() {
        if (beRev == null) {
            beRev = new Array<AggregatedElementRevision>();
        }
        return this.beRev;
    }

    public s3000l.OperationalTask.Secs getSecs() {
        return secs;
    }

    public void setSecs(s3000l.OperationalTask.Secs value) {
        this.secs = value;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public AggregatedElement() {
		super("http://www.asd-europe.org/s-series/s3000l", "AggregatedElement");
	}

}
