/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:00 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class AllowedProductConfigurationByConfigurationIdentifier extends EcRemoteLinkedData {

    protected AllowedProductConfigurationIdentifier prodConfId;
    protected AuthorityToOperate authToOp;
    protected Array<NestedAllowedProductConfigurationRelationship> nestedPC;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public AllowedProductConfigurationIdentifier getProdConfId() {
        return prodConfId;
    }

    public void setProdConfId(AllowedProductConfigurationIdentifier value) {
        this.prodConfId = value;
    }

    public AuthorityToOperate getAuthToOp() {
        return authToOp;
    }

    public void setAuthToOp(AuthorityToOperate value) {
        this.authToOp = value;
    }

    public Array<NestedAllowedProductConfigurationRelationship> getNestedPC() {
        if (nestedPC == null) {
            nestedPC = new Array<NestedAllowedProductConfigurationRelationship>();
        }
        return this.nestedPC;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public AllowedProductConfigurationByConfigurationIdentifier() {
		super("http://www.asd-europe.org/s-series/s3000l", "AllowedProductConfigurationByConfigurationIdentifier");
	}

}
