/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:00 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ApplicabilityEvaluationByAssertionOfCondition extends EcRemoteLinkedData {

    protected ConditionTypeReference condTypeRef;
    protected ConditionInstanceReference condInstRef;
    protected ConditionTypeValueReference assertValue;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public ConditionTypeReference getCondTypeRef() {
        return condTypeRef;
    }

    public void setCondTypeRef(ConditionTypeReference value) {
        this.condTypeRef = value;
    }

    public ConditionInstanceReference getCondInstRef() {
        return condInstRef;
    }

    public void setCondInstRef(ConditionInstanceReference value) {
        this.condInstRef = value;
    }

    public ConditionTypeValueReference getAssertValue() {
        return assertValue;
    }

    public void setAssertValue(ConditionTypeValueReference value) {
        this.assertValue = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public ApplicabilityEvaluationByAssertionOfCondition() {
		super("http://www.asd-europe.org/s-series/s3000l", "ApplicabilityEvaluationByAssertionOfCondition");
	}

}
