/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:18 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ApplicabilityStatementIdentifier extends EcRemoteLinkedData {

    protected OrganizationReference setBy;

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public ApplicabilityStatementIdentifier() {
		super("http://www.asd-europe.org/s-series/s3000l", "ApplicabilityStatementIdentifier");
	}

}
