/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:18 CDT 2019
 *
 **/

package s3000l;


public enum AreaRateUnit {

    FM,
    HS,
    QC,
    QD,
    SF,
    SI,
    SM,
    MN,
    SY;
}
