/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:00 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s6000t.SubtaskTrainingLevelDecision;

public class AuthorityDrivenTaskRequirement extends EcRemoteLinkedData {

    protected TaskRequirementIdentifier trId;
    protected TaskRequirementAuthoritySourceType authType;
    protected TaskRequirementAuthority auth;
    protected Array<TaskRequirementRevision> trRev;
    protected s3000l.OperationalTask.Secs secs;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected SubtaskTrainingLevelDecision.Applic applic;
    protected String uid;
    protected CrudCodeValues crud;

    public TaskRequirementIdentifier getTrId() {
        return trId;
    }

    public void setTrId(TaskRequirementIdentifier value) {
        this.trId = value;
    }

    public TaskRequirementAuthoritySourceType getAuthType() {
        return authType;
    }

    public void setAuthType(TaskRequirementAuthoritySourceType value) {
        this.authType = value;
    }

    public TaskRequirementAuthority getAuth() {
        return auth;
    }

    public void setAuth(TaskRequirementAuthority value) {
        this.auth = value;
    }

    public Array<TaskRequirementRevision> getTrRev() {
        if (trRev == null) {
            trRev = new Array<TaskRequirementRevision>();
        }
        return this.trRev;
    }

    public s3000l.OperationalTask.Secs getSecs() {
        return secs;
    }

    public void setSecs(s3000l.OperationalTask.Secs value) {
        this.secs = value;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public SubtaskTrainingLevelDecision.Applic getApplic() {
        return applic;
    }

    public void setApplic(SubtaskTrainingLevelDecision.Applic value) {
        this.applic = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public AuthorityDrivenTaskRequirement() {
		super("http://www.asd-europe.org/s-series/s3000l", "AuthorityDrivenTaskRequirement");
	}

}
