/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:00 CDT 2019
 *
 **/

package s3000l;


public enum BinaryUnit {

    BIT,
    B,
    GB,
    KB,
    MB,
    OC,
    PB,
    TB;
}
