/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s3000l;


public enum BreakdownTypeCodeValues {

    ASD,
    FAM,
    FU,
    HY,
    IP,
    PH,
    SY,
    ZONE;
}
