/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:52 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class BreakdownElementUsageInBreakdownReference extends EcRemoteLinkedData {

    protected Object uidRef;

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public BreakdownElementUsageInBreakdownReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "BreakdownElementUsageInBreakdownReference");
	}

}
