/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:52 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class BreakdownElementReference extends EcRemoteLinkedData {

    protected BreakdownElementIdentifier beId;
    protected Object uidRef;

    public BreakdownElementIdentifier getBeId() {
        return beId;
    }

    public void setBeId(BreakdownElementIdentifier value) {
        this.beId = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public BreakdownElementReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "BreakdownElementReference");
	}

}
