/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:18 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class BreakdownElementStructureReference extends EcRemoteLinkedData {

    protected Object uidRef;

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public BreakdownElementStructureReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "BreakdownElementStructureReference");
	}

}
