/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:00 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class BreakdownElementStructure extends EcRemoteLinkedData {

    protected Array<ReferenceDesignator> rfd;
    protected QuantityOfChildElement qty;
    protected BreakdownElementUsageInBreakdownReference beChildRef;
    protected Array<BreakdownElementStructureRelationship> relatedElem;
    protected String uid;
    protected CrudCodeValues crud;

    public Array<ReferenceDesignator> getRfd() {
        if (rfd == null) {
            rfd = new Array<ReferenceDesignator>();
        }
        return this.rfd;
    }

    public QuantityOfChildElement getQty() {
        return qty;
    }

    public void setQty(QuantityOfChildElement value) {
        this.qty = value;
    }

    public BreakdownElementUsageInBreakdownReference getBeChildRef() {
        return beChildRef;
    }

    public void setBeChildRef(BreakdownElementUsageInBreakdownReference value) {
        this.beChildRef = value;
    }

    public Array<BreakdownElementStructureRelationship> getRelatedElem() {
        if (relatedElem == null) {
            relatedElem = new Array<BreakdownElementStructureRelationship>();
        }
        return this.relatedElem;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public BreakdownElementStructure() {
		super("http://www.asd-europe.org/s-series/s3000l", "BreakdownElementStructure");
	}

}
