/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:52 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class BreakdownElementRevisionRelationship extends EcRemoteLinkedData {

    protected BreakdownElementRelationshipType relType;
    protected BreakdownElementRevisionReference beRef;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public BreakdownElementRelationshipType getRelType() {
        return relType;
    }

    public void setRelType(BreakdownElementRelationshipType value) {
        this.relType = value;
    }

    public BreakdownElementRevisionReference getBeRef() {
        return beRef;
    }

    public void setBeRef(BreakdownElementRevisionReference value) {
        this.beRef = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public BreakdownElementRevisionRelationship() {
		super("http://www.asd-europe.org/s-series/s3000l", "BreakdownElementRevisionRelationship");
	}

}
