/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class BreakdownRevision extends EcRemoteLinkedData {

    protected BreakdownRevisionIdentifier bkdnRevId;
    protected BreakdownRevisionStatus status;
    protected BreakdownRevisionCreationDate bkdnRevDate;
    protected Array<BreakdownElementUsageInBreakdown> beUsage;
    protected ConditionInstance.Docs docs;
    protected ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public BreakdownRevisionIdentifier getBkdnRevId() {
        return bkdnRevId;
    }

    public void setBkdnRevId(BreakdownRevisionIdentifier value) {
        this.bkdnRevId = value;
    }

    public BreakdownRevisionStatus getStatus() {
        return status;
    }

    public void setStatus(BreakdownRevisionStatus value) {
        this.status = value;
    }

    public BreakdownRevisionCreationDate getBkdnRevDate() {
        return bkdnRevDate;
    }

    public void setBkdnRevDate(BreakdownRevisionCreationDate value) {
        this.bkdnRevDate = value;
    }

    public Array<BreakdownElementUsageInBreakdown> getBeUsage() {
        if (beUsage == null) {
            beUsage = new Array<BreakdownElementUsageInBreakdown>();
        }
        return this.beUsage;
    }

    public ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(ConditionInstance.Docs value) {
        this.docs = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public BreakdownRevision() {
		super("http://www.asd-europe.org/s-series/s3000l", "BreakdownRevision");
	}

}
