/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:00 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ChangeRequestReference extends EcRemoteLinkedData {

    protected ChangeRequestIdentifier crId;
    protected Object uidRef;

    public ChangeRequestIdentifier getCrId() {
        return crId;
    }

    public void setCrId(ChangeRequestIdentifier value) {
        this.crId = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public ChangeRequestReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "ChangeRequestReference");
	}

}
