/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:00 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class CircuitBreaker extends EcRemoteLinkedData {

    protected CircuitBreakerIdentifier cbId;
    protected CircuitBreakerName name;
    protected CircuitBreakerType cbType;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public CircuitBreakerIdentifier getCbId() {
        return cbId;
    }

    public void setCbId(CircuitBreakerIdentifier value) {
        this.cbId = value;
    }

    public CircuitBreakerName getName() {
        return name;
    }

    public void setName(CircuitBreakerName value) {
        this.name = value;
    }

    public CircuitBreakerType getCbType() {
        return cbType;
    }

    public void setCbType(CircuitBreakerType value) {
        this.cbType = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public CircuitBreaker() {
		super("http://www.asd-europe.org/s-series/s3000l", "CircuitBreaker");
	}

}
