/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:53 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ConditionTypeReference extends EcRemoteLinkedData {

    protected ConditionTypeName condName;
    protected Object uidRef;

    public ConditionTypeName getCondName() {
        return condName;
    }

    public void setCondName(ConditionTypeName value) {
        this.condName = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public ConditionTypeReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "ConditionTypeReference");
	}

}
