/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ConditionTypeValueReference extends EcRemoteLinkedData {

    protected String code;
    protected ConditionTypePropertyValue propValue;
    protected Object uidRef;

    public String getCode() {
        return code;
    }

    public void setCode(String value) {
        this.code = value;
    }

    public ConditionTypePropertyValue getPropValue() {
        return propValue;
    }

    public void setPropValue(ConditionTypePropertyValue value) {
        this.propValue = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public ConditionTypeValueReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "ConditionTypeValueReference");
	}

}
