/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:00 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class ConditionInstance extends EcRemoteLinkedData {

    protected ConditionInstanceIdentifier condInstId;
    protected ConditionInstanceName name;
    protected ConditionInstanceDescription condInstDescr;
    protected ConditionInstance.Docs docs;
    protected ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public ConditionInstanceIdentifier getCondInstId() {
        return condInstId;
    }

    public void setCondInstId(ConditionInstanceIdentifier value) {
        this.condInstId = value;
    }

    public ConditionInstanceName getName() {
        return name;
    }

    public void setName(ConditionInstanceName value) {
        this.name = value;
    }

    public ConditionInstanceDescription getCondInstDescr() {
        return condInstDescr;
    }

    public void setCondInstDescr(ConditionInstanceDescription value) {
        this.condInstDescr = value;
    }

    public ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(ConditionInstance.Docs value) {
        this.docs = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

    public static class Docs {

        protected Array<DocumentAssignment> doc;

        public Array<DocumentAssignment> getDoc() {
            if (doc == null) {
                doc = new Array<DocumentAssignment>();
            }
            return this.doc;
        }

    }

    public static class Rmks {

        protected Array<Remark> rmk;

        public Array<Remark> getRmk() {
            if (rmk == null) {
                rmk = new Array<Remark>();
            }
            return this.rmk;
        }

    }

	public ConditionInstance() {
		super("http://www.asd-europe.org/s-series/s3000l", "ConditionInstance");
	}

}
