/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class Damage extends EcRemoteLinkedData {

    protected DamageDescription dmgDescr;
    protected DamageFamily dmgFamily;
    protected Array<PossibleSpecialEventEffect> cause;
    protected ConditionInstance.Docs docs;
    protected ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public DamageDescription getDmgDescr() {
        return dmgDescr;
    }

    public void setDmgDescr(DamageDescription value) {
        this.dmgDescr = value;
    }

    public DamageFamily getDmgFamily() {
        return dmgFamily;
    }

    public void setDmgFamily(DamageFamily value) {
        this.dmgFamily = value;
    }

    public Array<PossibleSpecialEventEffect> getCause() {
        if (cause == null) {
            cause = new Array<PossibleSpecialEventEffect>();
        }
        return this.cause;
    }

    public ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(ConditionInstance.Docs value) {
        this.docs = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public Damage() {
		super("http://www.asd-europe.org/s-series/s3000l", "Damage");
	}

}
