/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:01 CDT 2019
 *
 **/

package s3000l;


public enum DataTransferRateUnit {

    BIPS,
    BPS,
    KBIS,
    KBS,
    MBIS,
    MBS,
    GBIS,
    GBS;
}
