/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class DataModuleCode extends EcRemoteLinkedData {

    protected DataModuleCodeClassValues clazz;
    protected OrganizationReference setBy;

    public DataModuleCodeClassValues getClazz() {
        return clazz;
    }

    public void setClazz(DataModuleCodeClassValues value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public DataModuleCode() {
		super("http://www.asd-europe.org/s-series/s3000l", "DataModuleCode");
	}

}
