/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:53 CDT 2019
 *
 **/

package s3000l;


public enum DetectionMeanTypeCodeValues {

    PBIT,
    CBIT,
    IBIT,
    GSE;
}
