/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class DocumentAssignment extends EcRemoteLinkedData {

    protected DocumentAssignmentRole docRole;
    protected DocumentPortion docPortion;
    protected DocumentReference docRef;
    protected DocumentIssueReference docIssRef;
    protected ConditionInstance.Rmks rmks;
    protected ProductName.Applic applic;
    protected String uid;
    protected CrudCodeValues crud;

    public DocumentAssignmentRole getDocRole() {
        return docRole;
    }

    public void setDocRole(DocumentAssignmentRole value) {
        this.docRole = value;
    }

    public DocumentPortion getDocPortion() {
        return docPortion;
    }

    public void setDocPortion(DocumentPortion value) {
        this.docPortion = value;
    }

    public DocumentReference getDocRef() {
        return docRef;
    }

    public void setDocRef(DocumentReference value) {
        this.docRef = value;
    }

    public DocumentIssueReference getDocIssRef() {
        return docIssRef;
    }

    public void setDocIssRef(DocumentIssueReference value) {
        this.docIssRef = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(ProductName.Applic value) {
        this.applic = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public DocumentAssignment() {
		super("http://www.asd-europe.org/s-series/s3000l", "DocumentAssignment");
	}

}
