/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:53 CDT 2019
 *
 **/

package s3000l;


public enum EventRateUnit {

    A,
    C,
    DL,
    DT,
    EM,
    ES,
    FI,
    FC,
    FH,
    LD,
    LA,
    OH,
    OV,
    OC,
    OP,
    RD,
    SD,
    SO,
    S,
    ST,
    SN,
    TO,
    TA,
    TV,
    VL,
    VT;
}
