/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:01 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class ExternalDocument extends EcRemoteLinkedData {

    protected Array<DocumentIdentifier> docId;
    protected DocumentTitle docTitle;
    protected DocumentType docType;
    protected DocumentLocation docLoc;
    protected Array<ExternalDocumentIssue> docIss;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public Array<DocumentIdentifier> getDocId() {
        if (docId == null) {
            docId = new Array<DocumentIdentifier>();
        }
        return this.docId;
    }

    public DocumentTitle getDocTitle() {
        return docTitle;
    }

    public void setDocTitle(DocumentTitle value) {
        this.docTitle = value;
    }

    public DocumentType getDocType() {
        return docType;
    }

    public void setDocType(DocumentType value) {
        this.docType = value;
    }

    public DocumentLocation getDocLoc() {
        return docLoc;
    }

    public void setDocLoc(DocumentLocation value) {
        this.docLoc = value;
    }

    public Array<ExternalDocumentIssue> getDocIss() {
        if (docIss == null) {
            docIss = new Array<ExternalDocumentIssue>();
        }
        return this.docIss;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public ExternalDocument() {
		super("http://www.asd-europe.org/s-series/s3000l", "ExternalDocument");
	}

}
