/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Date;

public class FailureModeDetectionAbilityRating extends EcRemoteLinkedData {

    protected FailureModeDetectionAbilityRatingCodeValues code;
    protected ProductName.Applic applic;
    protected ConditionInstance.Docs docs;
    protected ConditionInstance.Rmks rmks;
    protected Date date;

    public FailureModeDetectionAbilityRatingCodeValues getCode() {
        return code;
    }

    public void setCode(FailureModeDetectionAbilityRatingCodeValues value) {
        this.code = value;
    }

    public ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(ProductName.Applic value) {
        this.applic = value;
    }

    public ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(ConditionInstance.Docs value) {
        this.docs = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date value) {
        this.date = value;
    }

	public FailureModeDetectionAbilityRating() {
		super("http://www.asd-europe.org/s-series/s3000l", "FailureModeDetectionAbilityRating");
	}

}
