/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class HardwareElement extends EcRemoteLinkedData {

    protected Array<BreakdownElementIdentifier> beId;
    protected Array<BreakdownElementName> name;
    protected BreakdownElementEssentiality esc;
    protected HardwareElementType beType;
    protected Array<HardwareElementRevision> beRev;
    protected OperationalTask.Secs secs;
    protected DownTime.OrgInfos orgInfos;
    protected ConditionInstance.Docs docs;
    protected ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public Array<BreakdownElementIdentifier> getBeId() {
        if (beId == null) {
            beId = new Array<BreakdownElementIdentifier>();
        }
        return this.beId;
    }

    public Array<BreakdownElementName> getName() {
        if (name == null) {
            name = new Array<BreakdownElementName>();
        }
        return this.name;
    }

    public BreakdownElementEssentiality getEsc() {
        return esc;
    }

    public void setEsc(BreakdownElementEssentiality value) {
        this.esc = value;
    }

    public HardwareElementType getBeType() {
        return beType;
    }

    public void setBeType(HardwareElementType value) {
        this.beType = value;
    }

    public Array<HardwareElementRevision> getBeRev() {
        if (beRev == null) {
            beRev = new Array<HardwareElementRevision>();
        }
        return this.beRev;
    }

    public OperationalTask.Secs getSecs() {
        return secs;
    }

    public void setSecs(OperationalTask.Secs value) {
        this.secs = value;
    }

    public DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(ConditionInstance.Docs value) {
        this.docs = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public HardwareElement() {
		super("http://www.asd-europe.org/s-series/s3000l", "HardwareElement");
	}

}
