/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:01 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class HardwareElementPartRealization extends EcRemoteLinkedData {

    protected PartAsDesignedReference partRef;
    protected HardwareElementPartRealization.UsableOnList usableOnList;
    protected s3000l.PartAsDesignedPartsList.ApcEfys apcEfys;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public PartAsDesignedReference getPartRef() {
        return partRef;
    }

    public void setPartRef(PartAsDesignedReference value) {
        this.partRef = value;
    }

    public HardwareElementPartRealization.UsableOnList getUsableOnList() {
        return usableOnList;
    }

    public void setUsableOnList(HardwareElementPartRealization.UsableOnList value) {
        this.usableOnList = value;
    }

    public s3000l.PartAsDesignedPartsList.ApcEfys getApcEfys() {
        return apcEfys;
    }

    public void setApcEfys(s3000l.PartAsDesignedPartsList.ApcEfys value) {
        this.apcEfys = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

    public static class UsableOnList {

        protected Array<ItemInProductVariant> usableOn;

        public Array<ItemInProductVariant> getUsableOn() {
            if (usableOn == null) {
                usableOn = new Array<ItemInProductVariant>();
            }
            return this.usableOn;
        }

    }

	public HardwareElementPartRealization() {
		super("http://www.asd-europe.org/s-series/s3000l", "HardwareElementPartRealization");
	}

}
