/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:01 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class HardwareElementPartRealizationReference extends EcRemoteLinkedData {

    protected Object uidRef;

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public HardwareElementPartRealizationReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "HardwareElementPartRealizationReference");
	}

}
