/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:20 CDT 2019
 *
 **/

package s3000l;


public enum HardwarePartEnvironmentalAspectPlannedDisposalClassCodeValues {

    HARM,
    ACID,
    OZON,
    GREEN,
    WASTE,
    BURN,
    RECY;
}
