/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:01 CDT 2019
 *
 **/

package s3000l;


public enum LengthRateUnit {

    CM,
    DA,
    DE,
    FM,
    FT,
    HM,
    HF,
    HY,
    IN,
    LM,
    KM,
    NM,
    MR,
    MI,
    MM,
    MF,
    YD;
}
