/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:54 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class LsaFailureMode extends EcRemoteLinkedData {

    protected FailureModeIdentifier fmId;
    protected FailureModeDescription fmDescr;
    protected Array<FailureModeFailureRate> failRte;
    protected Array<FailureModeDetectionAbilityRating> detectRtg;
    protected FailureModeDetectionAbilityDescription detectDescr;
    protected FailureModeLocalizationAbilityRating lznRtg;
    protected FailureModeLocalizationAbilityDescription lznDescr;
    protected FailureModeIsolationRate isolRte;
    protected Array<Object> failureModeEffectNonAbstractClasses;
    protected Array<FailureModeReference> techFmRef;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected s3000l.ProductName.Applic applic;
    protected String uid;
    protected CrudCodeValues crud;

    public FailureModeIdentifier getFmId() {
        return fmId;
    }

    public void setFmId(FailureModeIdentifier value) {
        this.fmId = value;
    }

    public FailureModeDescription getFmDescr() {
        return fmDescr;
    }

    public void setFmDescr(FailureModeDescription value) {
        this.fmDescr = value;
    }

    public Array<FailureModeFailureRate> getFailRte() {
        if (failRte == null) {
            failRte = new Array<FailureModeFailureRate>();
        }
        return this.failRte;
    }

    public Array<FailureModeDetectionAbilityRating> getDetectRtg() {
        if (detectRtg == null) {
            detectRtg = new Array<FailureModeDetectionAbilityRating>();
        }
        return this.detectRtg;
    }

    public FailureModeDetectionAbilityDescription getDetectDescr() {
        return detectDescr;
    }

    public void setDetectDescr(FailureModeDetectionAbilityDescription value) {
        this.detectDescr = value;
    }

    public FailureModeLocalizationAbilityRating getLznRtg() {
        return lznRtg;
    }

    public void setLznRtg(FailureModeLocalizationAbilityRating value) {
        this.lznRtg = value;
    }

    public FailureModeLocalizationAbilityDescription getLznDescr() {
        return lznDescr;
    }

    public void setLznDescr(FailureModeLocalizationAbilityDescription value) {
        this.lznDescr = value;
    }

    public FailureModeIsolationRate getIsolRte() {
        return isolRte;
    }

    public void setIsolRte(FailureModeIsolationRate value) {
        this.isolRte = value;
    }

    public Array<Object> getFailureModeEffectNonAbstractClasses() {
        if (failureModeEffectNonAbstractClasses == null) {
            failureModeEffectNonAbstractClasses = new Array<Object>();
        }
        return this.failureModeEffectNonAbstractClasses;
    }

    public Array<FailureModeReference> getTechFmRef() {
        if (techFmRef == null) {
            techFmRef = new Array<FailureModeReference>();
        }
        return this.techFmRef;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public s3000l.ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(s3000l.ProductName.Applic value) {
        this.applic = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public LsaFailureMode() {
		super("http://www.asd-europe.org/s-series/s3000l", "LsaFailureMode");
	}

}
