/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:20 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class MaintenanceLevelReference extends EcRemoteLinkedData {

    protected MaintenanceLevelIdentifier mlvId;
    protected Object uidRef;

    public MaintenanceLevelIdentifier getMlvId() {
        return mlvId;
    }

    public void setMlvId(MaintenanceLevelIdentifier value) {
        this.mlvId = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public MaintenanceLevelReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "MaintenanceLevelReference");
	}

}
