/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:54 CDT 2019
 *
 **/

package s3000l;


public enum MassRateUnit {

    CG,
    DC,
    DG,
    DM,
    HG,
    GM,
    HW,
    KG,
    LT,
    MG,
    TM,
    OZ,
    QK,
    QN,
    LB,
    TO,
    TN;
}
