/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Date;

public class MessageCreationDate extends EcRemoteLinkedData {

    protected Date dateTime;

    public Date getDateTime() {
        return dateTime;
    }

    public void setDateTime(Date value) {
        this.dateTime = value;
    }

	public MessageCreationDate() {
		super("http://www.asd-europe.org/s-series/s3000l", "MessageCreationDate");
	}

}
