/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:54 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class OperatingLocationTypeIdentifier extends EcRemoteLinkedData {

    protected OperatingLocationTypeIdentifierClassValues clazz;
    protected OrganizationReference setBy;

    public OperatingLocationTypeIdentifierClassValues getClazz() {
        return clazz;
    }

    public void setClazz(OperatingLocationTypeIdentifierClassValues value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public OperatingLocationTypeIdentifier() {
		super("http://www.asd-europe.org/s-series/s3000l", "OperatingLocationTypeIdentifier");
	}

}
