/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:21 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class OperatingLocationType extends EcRemoteLinkedData {

    protected OperatingLocationTypeIdentifier opTypeId;
    protected OperatingLocationTypeName name;
    protected OperatingLocationTypeDescription opTypeDescr;
    protected NumberOfOperatingLocations nrOfLoc;
    protected MaintenanceCapabilityAtOperatingLocationType maintCap;
    protected OrganizationReference orgRef;
    protected ConditionInstance.Docs docs;
    protected ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public OperatingLocationTypeIdentifier getOpTypeId() {
        return opTypeId;
    }

    public void setOpTypeId(OperatingLocationTypeIdentifier value) {
        this.opTypeId = value;
    }

    public OperatingLocationTypeName getName() {
        return name;
    }

    public void setName(OperatingLocationTypeName value) {
        this.name = value;
    }

    public OperatingLocationTypeDescription getOpTypeDescr() {
        return opTypeDescr;
    }

    public void setOpTypeDescr(OperatingLocationTypeDescription value) {
        this.opTypeDescr = value;
    }

    public NumberOfOperatingLocations getNrOfLoc() {
        return nrOfLoc;
    }

    public void setNrOfLoc(NumberOfOperatingLocations value) {
        this.nrOfLoc = value;
    }

    public MaintenanceCapabilityAtOperatingLocationType getMaintCap() {
        return maintCap;
    }

    public void setMaintCap(MaintenanceCapabilityAtOperatingLocationType value) {
        this.maintCap = value;
    }

    public OrganizationReference getOrgRef() {
        return orgRef;
    }

    public void setOrgRef(OrganizationReference value) {
        this.orgRef = value;
    }

    public ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(ConditionInstance.Docs value) {
        this.docs = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public OperatingLocationType() {
		super("http://www.asd-europe.org/s-series/s3000l", "OperatingLocationType");
	}

}
