/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class OperatingLocationReference extends EcRemoteLinkedData {

    protected OperatingLocationIdentifier opLocId;
    protected Object uidRef;

    public OperatingLocationIdentifier getOpLocId() {
        return opLocId;
    }

    public void setOpLocId(OperatingLocationIdentifier value) {
        this.opLocId = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public OperatingLocationReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "OperatingLocationReference");
	}

}
