/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class OrganizationReference extends EcRemoteLinkedData {

    protected OrganizationIdentifier orgId;
    protected Object uidRef;

    public OrganizationIdentifier getOrgId() {
        return orgId;
    }

    public void setOrgId(OrganizationIdentifier value) {
        this.orgId = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public OrganizationReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "OrganizationReference");
	}

}
