/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class PartAsDesignedPartsList extends EcRemoteLinkedData {

    protected PartsListType pListType;
    protected PartsListRevisionIdentifier pListRevId;
    protected Array<PartAsDesignedPartsListEntry> pListEntry;
    protected PartAsDesignedPartsList.ApcEfys apcEfys;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public PartsListType getPListType() {
        return pListType;
    }

    public void setPListType(PartsListType value) {
        this.pListType = value;
    }

    public PartsListRevisionIdentifier getPListRevId() {
        return pListRevId;
    }

    public void setPListRevId(PartsListRevisionIdentifier value) {
        this.pListRevId = value;
    }

    public Array<PartAsDesignedPartsListEntry> getPListEntry() {
        if (pListEntry == null) {
            pListEntry = new Array<PartAsDesignedPartsListEntry>();
        }
        return this.pListEntry;
    }

    public PartAsDesignedPartsList.ApcEfys getApcEfys() {
        return apcEfys;
    }

    public void setApcEfys(PartAsDesignedPartsList.ApcEfys value) {
        this.apcEfys = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

    public static class ApcEfys {

        protected Array<ItemInAllowedProductConfiguration> apcEfy;

        public Array<ItemInAllowedProductConfiguration> getApcEfy() {
            if (apcEfy == null) {
                apcEfy = new Array<ItemInAllowedProductConfiguration>();
            }
            return this.apcEfy;
        }

    }

	public PartAsDesignedPartsList() {
		super("http://www.asd-europe.org/s-series/s3000l", "PartAsDesignedPartsList");
	}

}
