/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:21 CDT 2019
 *
 **/

package s3000l;


public enum PartIdentifierClassValues {

    CPNO,
    OEM,
    PNO,
    SPNO,
    REF,
    NSN,
    STD;
}
