/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class PartAsDesignedPartsListEntry extends EcRemoteLinkedData {

    protected QuantityOfChildElement qty;
    protected ReferenceDesignator rfd;
    protected Array<PartsListEntryIdentifier> posId;
    protected PhysicalReplaceability repl;
    protected Array<PhysicalReplaceabilityStrategy> rly;
    protected PartAsDesignedReference partRef;
    protected Array<SubstitutePartAsDesignedRelationship> substPart;
    protected s3000l.PartAsDesignedPartsList.ApcEfys apcEfys;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public QuantityOfChildElement getQty() {
        return qty;
    }

    public void setQty(QuantityOfChildElement value) {
        this.qty = value;
    }

    public ReferenceDesignator getRfd() {
        return rfd;
    }

    public void setRfd(ReferenceDesignator value) {
        this.rfd = value;
    }

    public Array<PartsListEntryIdentifier> getPosId() {
        if (posId == null) {
            posId = new Array<PartsListEntryIdentifier>();
        }
        return this.posId;
    }

    public PhysicalReplaceability getRepl() {
        return repl;
    }

    public void setRepl(PhysicalReplaceability value) {
        this.repl = value;
    }

    public Array<PhysicalReplaceabilityStrategy> getRly() {
        if (rly == null) {
            rly = new Array<PhysicalReplaceabilityStrategy>();
        }
        return this.rly;
    }

    public PartAsDesignedReference getPartRef() {
        return partRef;
    }

    public void setPartRef(PartAsDesignedReference value) {
        this.partRef = value;
    }

    public Array<SubstitutePartAsDesignedRelationship> getSubstPart() {
        if (substPart == null) {
            substPart = new Array<SubstitutePartAsDesignedRelationship>();
        }
        return this.substPart;
    }

    public s3000l.PartAsDesignedPartsList.ApcEfys getApcEfys() {
        return apcEfys;
    }

    public void setApcEfys(s3000l.PartAsDesignedPartsList.ApcEfys value) {
        this.apcEfys = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public PartAsDesignedPartsListEntry() {
		super("http://www.asd-europe.org/s-series/s3000l", "PartAsDesignedPartsListEntry");
	}

}
