/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;


public enum PartMaturityClassCodeValues {

    NEW,
    MOD_L,
    MOD_M,
    COTS,
    CFE,
    OBS;
}
