/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:21 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class PlannedTaskTarget extends EcRemoteLinkedData {

    protected Array<SupportingTaskTarget.TaskFreq> taskFreq;
    protected TaskRef taskRef;
    protected Array<AllocatedMaintenanceLevel> maintLevel;
    protected DownTime.OrgInfos orgInfos;
    protected ConditionInstance.Docs docs;
    protected ConditionInstance.Rmks rmks;
    protected ProductName.Applic applic;
    protected PlannedTaskTarget.TimeLimits timeLimits;
    protected String uid;
    protected CrudCodeValues crud;

    public Array<SupportingTaskTarget.TaskFreq> getTaskFreq() {
        if (taskFreq == null) {
            taskFreq = new Array<SupportingTaskTarget.TaskFreq>();
        }
        return this.taskFreq;
    }

    public TaskRef getTaskRef() {
        return taskRef;
    }

    public void setTaskRef(TaskRef value) {
        this.taskRef = value;
    }

    public Array<AllocatedMaintenanceLevel> getMaintLevel() {
        if (maintLevel == null) {
            maintLevel = new Array<AllocatedMaintenanceLevel>();
        }
        return this.maintLevel;
    }

    public DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(ConditionInstance.Docs value) {
        this.docs = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(ProductName.Applic value) {
        this.applic = value;
    }

    public PlannedTaskTarget.TimeLimits getTimeLimits() {
        return timeLimits;
    }

    public void setTimeLimits(PlannedTaskTarget.TimeLimits value) {
        this.timeLimits = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

    public static class TimeLimits {

        protected Array<Object> timeLimitNonAbstractClasses;

        public Array<Object> getTimeLimitNonAbstractClasses() {
            if (timeLimitNonAbstractClasses == null) {
                timeLimitNonAbstractClasses = new Array<Object>();
            }
            return this.timeLimitNonAbstractClasses;
        }

    }

	public PlannedTaskTarget() {
		super("http://www.asd-europe.org/s-series/s3000l", "PlannedTaskTarget");
	}

}
