/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:54 CDT 2019
 *
 **/

package s3000l;


public enum ProductUsagePhaseCodeValues {

    OPER,
    TOFF,
    FLIGHT,
    MAINT,
    STOR,
    TRAN;
}
