/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:54 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ProjectReference extends EcRemoteLinkedData {

    protected ProjectIdentifier projId;
    protected Object uidRef;

    public ProjectIdentifier getProjId() {
        return projId;
    }

    public void setProjId(ProjectIdentifier value) {
        this.projId = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public ProjectReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "ProjectReference");
	}

}
