/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:21 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ProjectIdentifier extends EcRemoteLinkedData {

    protected ProjectIdentifierClassValues clazz;
    protected OrganizationReference setBy;

    public ProjectIdentifierClassValues getClazz() {
        return clazz;
    }

    public void setClazz(ProjectIdentifierClassValues value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public ProjectIdentifier() {
		super("http://www.asd-europe.org/s-series/s3000l", "ProjectIdentifier");
	}

}
