/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class PublicationModuleCode extends EcRemoteLinkedData {

    protected PublicationModuleCodeClassValues clazz;
    protected OrganizationReference setBy;

    public PublicationModuleCodeClassValues getClazz() {
        return clazz;
    }

    public void setClazz(PublicationModuleCodeClassValues value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public PublicationModuleCode() {
		super("http://www.asd-europe.org/s-series/s3000l", "PublicationModuleCode");
	}

}
