/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:21 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class QuantifiedSpecialEventOccurrence extends EcRemoteLinkedData {

    protected Array<SpecialEventOccurrenceRate> occRte;
    protected Array<ProductUsagePhaseReference> usagePhaseRef;
    protected ConditionInstance.Docs docs;
    protected ConditionInstance.Rmks rmks;
    protected ProductName.Applic applic;
    protected String uid;
    protected CrudCodeValues crud;

    public Array<SpecialEventOccurrenceRate> getOccRte() {
        if (occRte == null) {
            occRte = new Array<SpecialEventOccurrenceRate>();
        }
        return this.occRte;
    }

    public Array<ProductUsagePhaseReference> getUsagePhaseRef() {
        if (usagePhaseRef == null) {
            usagePhaseRef = new Array<ProductUsagePhaseReference>();
        }
        return this.usagePhaseRef;
    }

    public ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(ConditionInstance.Docs value) {
        this.docs = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(ProductName.Applic value) {
        this.applic = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public QuantifiedSpecialEventOccurrence() {
		super("http://www.asd-europe.org/s-series/s3000l", "QuantifiedSpecialEventOccurrence");
	}

}
