/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:54 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ResourceSpecificationIdentifier extends EcRemoteLinkedData {

    protected ResourceSpecificationIdentifierClassValues clazz;
    protected OrganizationReference setBy;

    public ResourceSpecificationIdentifierClassValues getClazz() {
        return clazz;
    }

    public void setClazz(ResourceSpecificationIdentifierClassValues value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public ResourceSpecificationIdentifier() {
		super("http://www.asd-europe.org/s-series/s3000l", "ResourceSpecificationIdentifier");
	}

}
