/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class S1000DPublicationModuleIssue extends EcRemoteLinkedData {

    protected PublicationModuleIssueNumber pmIssId;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public PublicationModuleIssueNumber getPmIssId() {
        return pmIssId;
    }

    public void setPmIssId(PublicationModuleIssueNumber value) {
        this.pmIssId = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public S1000DPublicationModuleIssue() {
		super("http://www.asd-europe.org/s-series/s3000l", "S1000DPublicationModuleIssue");
	}

}
