/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:54 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class S1000DDataModuleIssue extends EcRemoteLinkedData {

    protected DataModuleIssueNumber dmIssId;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public DataModuleIssueNumber getDmIssId() {
        return dmIssId;
    }

    public void setDmIssId(DataModuleIssueNumber value) {
        this.dmIssId = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public S1000DDataModuleIssue() {
		super("http://www.asd-europe.org/s-series/s3000l", "S1000DDataModuleIssue");
	}

}
