/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;


public enum SecurityClassCodeValues {

    C,
    CC,
    R,
    S,
    TS,
    UC;
}
