/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:54 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class SkillLevelReference extends EcRemoteLinkedData {

    protected TradeName tradeName;
    protected SkillLevelName skillLevName;
    protected Object uidRef;
    protected String uriRef;

    public TradeName getTradeName() {
        return tradeName;
    }

    public void setTradeName(TradeName value) {
        this.tradeName = value;
    }

    public SkillLevelName getSkillLevName() {
        return skillLevName;
    }

    public void setSkillLevName(SkillLevelName value) {
        this.skillLevName = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

    public String getUriRef() {
        return uriRef;
    }

    public void setUriRef(String value) {
        this.uriRef = value;
    }

	public SkillLevelReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "SkillLevelReference");
	}

}
