/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import s6000t.KnowledgeSkillAttitudeGapAnalysisItem;
import s6000t.TrainingPopulationItem;

public class SkillLevel extends EcRemoteLinkedData {

    protected SkillLevelName skillLevName;
    protected SkillLevelDescription skillLevDescr;
    protected TrainingPopulationItem trainPopDef;
    protected KnowledgeSkillAttitudeGapAnalysisItem ksaGaps;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public SkillLevelName getSkillLevName() {
        return skillLevName;
    }

    public void setSkillLevName(SkillLevelName value) {
        this.skillLevName = value;
    }

    public SkillLevelDescription getSkillLevDescr() {
        return skillLevDescr;
    }

    public void setSkillLevDescr(SkillLevelDescription value) {
        this.skillLevDescr = value;
    }

    public TrainingPopulationItem getTrainPopDef() {
        return trainPopDef;
    }

    public void setTrainPopDef(TrainingPopulationItem value) {
        this.trainPopDef = value;
    }

    public KnowledgeSkillAttitudeGapAnalysisItem getKsaGaps() {
        return ksaGaps;
    }

    public void setKsaGaps(KnowledgeSkillAttitudeGapAnalysisItem value) {
        this.ksaGaps = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public SkillLevel() {
		super("http://www.asd-europe.org/s-series/s3000l", "SkillLevel");
	}

}
