/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class SkillCode extends EcRemoteLinkedData {

    protected SkillCodeClassValues clazz;
    protected OrganizationReference setBy;

    public SkillCodeClassValues getClazz() {
        return clazz;
    }

    public void setClazz(SkillCodeClassValues value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public SkillCode() {
		super("http://www.asd-europe.org/s-series/s3000l", "SkillCode");
	}

}
