/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:55 CDT 2019
 *
 **/

package s3000l;


public enum SpecialEventGroupCodeValues {

    EXT,
    NPH,
    MET,
    ANI,
    HUM,
    CBT,
    MNU,
    INT,
    DYS,
    HET,
    VIB;
}
