/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class SpecialEventThresholdDefinition extends EcRemoteLinkedData {

    protected long nrOfEvnts;
    protected SpecialEventReference sEvntRef;
    protected ConditionInstance.Rmks rmks;
    protected ProductName.Applic applic;
    protected String uid;
    protected CrudCodeValues crud;

    public long getNrOfEvnts() {
        return nrOfEvnts;
    }

    public void setNrOfEvnts(long value) {
        this.nrOfEvnts = value;
    }

    public SpecialEventReference getSEvntRef() {
        return sEvntRef;
    }

    public void setSEvntRef(SpecialEventReference value) {
        this.sEvntRef = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(ProductName.Applic value) {
        this.applic = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public SpecialEventThresholdDefinition() {
		super("http://www.asd-europe.org/s-series/s3000l", "SpecialEventThresholdDefinition");
	}

}
