/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:21 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class SpecialEvent extends EcRemoteLinkedData {

    protected SpecialEventTitle evntTitle;
    protected SpecialEventDescription evntDescr;
    protected SpecialEventGroup evntGrp;
    protected Array<Object> specialEventOccurrenceNonAbstractClasses;
    protected ConditionInstance.Docs docs;
    protected ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public SpecialEventTitle getEvntTitle() {
        return evntTitle;
    }

    public void setEvntTitle(SpecialEventTitle value) {
        this.evntTitle = value;
    }

    public SpecialEventDescription getEvntDescr() {
        return evntDescr;
    }

    public void setEvntDescr(SpecialEventDescription value) {
        this.evntDescr = value;
    }

    public SpecialEventGroup getEvntGrp() {
        return evntGrp;
    }

    public void setEvntGrp(SpecialEventGroup value) {
        this.evntGrp = value;
    }

    public Array<Object> getSpecialEventOccurrenceNonAbstractClasses() {
        if (specialEventOccurrenceNonAbstractClasses == null) {
            specialEventOccurrenceNonAbstractClasses = new Array<Object>();
        }
        return this.specialEventOccurrenceNonAbstractClasses;
    }

    public ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(ConditionInstance.Docs value) {
        this.docs = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public SpecialEvent() {
		super("http://www.asd-europe.org/s-series/s3000l", "SpecialEvent");
	}

}
