/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s6000t.SubtaskTrainingLevelDecision;

public class SubtaskByExternalReference extends EcRemoteLinkedData {

    protected SubtaskIdentifier subtId;
    protected SubtaskRole subtRole;
    protected SubtaskName name;
    protected InformationCode infoCode;
    protected SubtaskDescription subtDescr;
    protected SubtaskDuration duration;
    protected SubtaskMaintenanceLocation maintLoc;
    protected Array<SubtaskEndItemObjectiveState> eiObjState;
    protected Array<SubtaskByExternalReference.AccParam> accParam;
    protected Array<Object> subtaskCircuitBreakerSettingsNonAbstractClasses;
    protected Array<SubtaskWarningCautionNote> wcn;
    protected SubtaskTimeline precSubt;
    protected Array<SubtaskInZone> inZone;
    protected Array<SubtaskTarget> subtTgt;
    protected Array<DocumentReference> docRef;
    protected s3000l.OperationalTask.Secs secs;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected SubtaskTrainingLevelDecision.Applic applic;
    protected s3000l.TaskRevision.Resources resources;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public SubtaskIdentifier getSubtId() {
        return subtId;
    }

    public void setSubtId(SubtaskIdentifier value) {
        this.subtId = value;
    }

    public SubtaskRole getSubtRole() {
        return subtRole;
    }

    public void setSubtRole(SubtaskRole value) {
        this.subtRole = value;
    }

    public SubtaskName getName() {
        return name;
    }

    public void setName(SubtaskName value) {
        this.name = value;
    }

    public InformationCode getInfoCode() {
        return infoCode;
    }

    public void setInfoCode(InformationCode value) {
        this.infoCode = value;
    }

    public SubtaskDescription getSubtDescr() {
        return subtDescr;
    }

    public void setSubtDescr(SubtaskDescription value) {
        this.subtDescr = value;
    }

    public SubtaskDuration getDuration() {
        return duration;
    }

    public void setDuration(SubtaskDuration value) {
        this.duration = value;
    }

    public SubtaskMaintenanceLocation getMaintLoc() {
        return maintLoc;
    }

    public void setMaintLoc(SubtaskMaintenanceLocation value) {
        this.maintLoc = value;
    }

    public Array<SubtaskEndItemObjectiveState> getEiObjState() {
        if (eiObjState == null) {
            eiObjState = new Array<SubtaskEndItemObjectiveState>();
        }
        return this.eiObjState;
    }

    public Array<SubtaskByExternalReference.AccParam> getAccParam() {
        if (accParam == null) {
            accParam = new Array<SubtaskByExternalReference.AccParam>();
        }
        return this.accParam;
    }

    public Array<Object> getSubtaskCircuitBreakerSettingsNonAbstractClasses() {
        if (subtaskCircuitBreakerSettingsNonAbstractClasses == null) {
            subtaskCircuitBreakerSettingsNonAbstractClasses = new Array<Object>();
        }
        return this.subtaskCircuitBreakerSettingsNonAbstractClasses;
    }

    public Array<SubtaskWarningCautionNote> getWcn() {
        if (wcn == null) {
            wcn = new Array<SubtaskWarningCautionNote>();
        }
        return this.wcn;
    }

    public SubtaskTimeline getPrecSubt() {
        return precSubt;
    }

    public void setPrecSubt(SubtaskTimeline value) {
        this.precSubt = value;
    }

    public Array<SubtaskInZone> getInZone() {
        if (inZone == null) {
            inZone = new Array<SubtaskInZone>();
        }
        return this.inZone;
    }

    public Array<SubtaskTarget> getSubtTgt() {
        if (subtTgt == null) {
            subtTgt = new Array<SubtaskTarget>();
        }
        return this.subtTgt;
    }

    public Array<DocumentReference> getDocRef() {
        if (docRef == null) {
            docRef = new Array<DocumentReference>();
        }
        return this.docRef;
    }

    public s3000l.OperationalTask.Secs getSecs() {
        return secs;
    }

    public void setSecs(s3000l.OperationalTask.Secs value) {
        this.secs = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public SubtaskTrainingLevelDecision.Applic getApplic() {
        return applic;
    }

    public void setApplic(SubtaskTrainingLevelDecision.Applic value) {
        this.applic = value;
    }

    public s3000l.TaskRevision.Resources getResources() {
        return resources;
    }

    public void setResources(s3000l.TaskRevision.Resources value) {
        this.resources = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

    public static class AccParam {

        protected SubtaskAcceptanceParameterDescription paraDescr;
        protected Array<SubtaskAcceptanceParameterValue> paraValue;
        protected s3000l.ConditionInstance.Docs docs;
        protected s3000l.ConditionInstance.Rmks rmks;
        protected SubtaskTrainingLevelDecision.Applic applic;

        public SubtaskAcceptanceParameterDescription getParaDescr() {
            return paraDescr;
        }

        public void setParaDescr(SubtaskAcceptanceParameterDescription value) {
            this.paraDescr = value;
        }

        public Array<SubtaskAcceptanceParameterValue> getParaValue() {
            if (paraValue == null) {
                paraValue = new Array<SubtaskAcceptanceParameterValue>();
            }
            return this.paraValue;
        }

        public s3000l.ConditionInstance.Docs getDocs() {
            return docs;
        }

        public void setDocs(s3000l.ConditionInstance.Docs value) {
            this.docs = value;
        }

        public s3000l.ConditionInstance.Rmks getRmks() {
            return rmks;
        }

        public void setRmks(s3000l.ConditionInstance.Rmks value) {
            this.rmks = value;
        }

        public SubtaskTrainingLevelDecision.Applic getApplic() {
            return applic;
        }

        public void setApplic(SubtaskTrainingLevelDecision.Applic value) {
            this.applic = value;
        }

    }

	public SubtaskByExternalReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "SubtaskByExternalReference");
	}

}
