/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s6000t.SubtaskTrainingLevelDecision;

public class SubtaskTimeline extends EcRemoteLinkedData {

    protected SubtaskTimelineEvent evnt;
    protected Array<SubtaskTimelineLag> lag;
    protected SubtaskRef subtRef;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected SubtaskTrainingLevelDecision.Applic applic;
    protected String uid;
    protected CrudCodeValues crud;

    public SubtaskTimelineEvent getEvnt() {
        return evnt;
    }

    public void setEvnt(SubtaskTimelineEvent value) {
        this.evnt = value;
    }

    public Array<SubtaskTimelineLag> getLag() {
        if (lag == null) {
            lag = new Array<SubtaskTimelineLag>();
        }
        return this.lag;
    }

    public SubtaskRef getSubtRef() {
        return subtRef;
    }

    public void setSubtRef(SubtaskRef value) {
        this.subtRef = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public SubtaskTrainingLevelDecision.Applic getApplic() {
        return applic;
    }

    public void setApplic(SubtaskTrainingLevelDecision.Applic value) {
        this.applic = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public SubtaskTimeline() {
		super("http://www.asd-europe.org/s-series/s3000l", "SubtaskTimeline");
	}

}
