/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import s6000t.SubtaskTrainingLevelDecision;

public class SubtaskCircuitBreakerSettingsTimeline extends EcRemoteLinkedData {

    protected SubtaskCircuitBreakerSettingsReference cbSettingRef;
    protected SubtaskTrainingLevelDecision.Applic applic;
    protected String uid;
    protected CrudCodeValues crud;

    public SubtaskCircuitBreakerSettingsReference getCbSettingRef() {
        return cbSettingRef;
    }

    public void setCbSettingRef(SubtaskCircuitBreakerSettingsReference value) {
        this.cbSettingRef = value;
    }

    public SubtaskTrainingLevelDecision.Applic getApplic() {
        return applic;
    }

    public void setApplic(SubtaskTrainingLevelDecision.Applic value) {
        this.applic = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public SubtaskCircuitBreakerSettingsTimeline() {
		super("http://www.asd-europe.org/s-series/s3000l", "SubtaskCircuitBreakerSettingsTimeline");
	}

}
