/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s3000l;


public enum SubtaskEndItemObjectiveStateCodeValues {

    TC,
    JC,
    UJ,
    SY,
    EL,
    EEL,
    AEL,
    IEL,
    HPE,
    AS,
    FU,
    DF,
    WS,
    CS;
}
