/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class SupportingTaskTarget extends EcRemoteLinkedData {

    protected Array<SupportingTaskTarget.TaskFreq> taskFreq;
    protected TaskRef taskRef;
    protected DownTime.OrgInfos orgInfos;
    protected ConditionInstance.Docs docs;
    protected ConditionInstance.Rmks rmks;
    protected ProductName.Applic applic;
    protected String uid;
    protected CrudCodeValues crud;

    public Array<SupportingTaskTarget.TaskFreq> getTaskFreq() {
        if (taskFreq == null) {
            taskFreq = new Array<SupportingTaskTarget.TaskFreq>();
        }
        return this.taskFreq;
    }

    public TaskRef getTaskRef() {
        return taskRef;
    }

    public void setTaskRef(TaskRef value) {
        this.taskRef = value;
    }

    public DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(ConditionInstance.Docs value) {
        this.docs = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(ProductName.Applic value) {
        this.applic = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

    public static class TaskFreq {

        protected Array<TaskFrequency> frequency;
        protected TaskFrequencyCalculationMethod calcMthd;
        protected ConditionInstance.Docs docs;
        protected ConditionInstance.Rmks rmks;
        protected ProductName.Applic applic;

        public Array<TaskFrequency> getFrequency() {
            if (frequency == null) {
                frequency = new Array<TaskFrequency>();
            }
            return this.frequency;
        }

        public TaskFrequencyCalculationMethod getCalcMthd() {
            return calcMthd;
        }

        public void setCalcMthd(TaskFrequencyCalculationMethod value) {
            this.calcMthd = value;
        }

        public ConditionInstance.Docs getDocs() {
            return docs;
        }

        public void setDocs(ConditionInstance.Docs value) {
            this.docs = value;
        }

        public ConditionInstance.Rmks getRmks() {
            return rmks;
        }

        public void setRmks(ConditionInstance.Rmks value) {
            this.rmks = value;
        }

        public ProductName.Applic getApplic() {
            return applic;
        }

        public void setApplic(ProductName.Applic value) {
            this.applic = value;
        }

    }

	public SupportingTaskTarget() {
		super("http://www.asd-europe.org/s-series/s3000l", "SupportingTaskTarget");
	}

}
