/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:03 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class TaskRevisionIdentifier extends EcRemoteLinkedData {

    protected TaskRevisionIdentifierClassValues clazz;
    protected OrganizationReference setBy;

    public TaskRevisionIdentifierClassValues getClazz() {
        return clazz;
    }

    public void setClazz(TaskRevisionIdentifierClassValues value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public TaskRevisionIdentifier() {
		super("http://www.asd-europe.org/s-series/s3000l", "TaskRevisionIdentifier");
	}

}
