/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class TaskFacilityResourceByReference extends EcRemoteLinkedData {

    protected Boolean fixed;
    protected Array<TaskResourceDuration> duration;
    protected TaskFacilityResourceQuantity qty;
    protected Array<TaskResourceRelationship> relRes;
    protected BreakdownElementReference beRef;
    protected PartAsDesignedReference partRef;
    protected ConditionInstance.Docs docs;
    protected ConditionInstance.Rmks rmks;
    protected ProductName.Applic applic;
    protected String uid;
    protected CrudCodeValues crud;

    public Boolean getFixed() {
        return fixed;
    }

    public void setFixed(Boolean value) {
        this.fixed = value;
    }

    public Array<TaskResourceDuration> getDuration() {
        if (duration == null) {
            duration = new Array<TaskResourceDuration>();
        }
        return this.duration;
    }

    public TaskFacilityResourceQuantity getQty() {
        return qty;
    }

    public void setQty(TaskFacilityResourceQuantity value) {
        this.qty = value;
    }

    public Array<TaskResourceRelationship> getRelRes() {
        if (relRes == null) {
            relRes = new Array<TaskResourceRelationship>();
        }
        return this.relRes;
    }

    public BreakdownElementReference getBeRef() {
        return beRef;
    }

    public void setBeRef(BreakdownElementReference value) {
        this.beRef = value;
    }

    public PartAsDesignedReference getPartRef() {
        return partRef;
    }

    public void setPartRef(PartAsDesignedReference value) {
        this.partRef = value;
    }

    public ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(ConditionInstance.Docs value) {
        this.docs = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(ProductName.Applic value) {
        this.applic = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public TaskFacilityResourceByReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "TaskFacilityResourceByReference");
	}

}
