/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:55 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class TaskRequirementAuthority extends EcRemoteLinkedData {

    protected OrganizationReference orgRef;

    public OrganizationReference getOrgRef() {
        return orgRef;
    }

    public void setOrgRef(OrganizationReference value) {
        this.orgRef = value;
    }

	public TaskRequirementAuthority() {
		super("http://www.asd-europe.org/s-series/s3000l", "TaskRequirementAuthority");
	}

}
