/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class TaskRequirementIdentifier extends EcRemoteLinkedData {

    protected TaskRequirementIdentifierClassValues clazz;
    protected OrganizationReference setBy;

    public TaskRequirementIdentifierClassValues getClazz() {
        return clazz;
    }

    public void setClazz(TaskRequirementIdentifierClassValues value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public TaskRequirementIdentifier() {
		super("http://www.asd-europe.org/s-series/s3000l", "TaskRequirementIdentifier");
	}

}
