/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:03 CDT 2019
 *
 **/

package s3000l;


public enum TaskOperabilityImpactCodeValues {

    NEQM,
    OPEQM,
    PMISS,
    FMISS,
    NMISS,
    TA;
}
