/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:03 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;
import s6000t.SubtaskTrainingLevelDecision;

public class TaskResourceRelationship extends EcRemoteLinkedData {

    protected TaskResourceRelationshipCategory relType;
    protected TaskResourceReference resRef;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected SubtaskTrainingLevelDecision.Applic applic;
    protected String uid;
    protected CrudCodeValues crud;

    public TaskResourceRelationshipCategory getRelType() {
        return relType;
    }

    public void setRelType(TaskResourceRelationshipCategory value) {
        this.relType = value;
    }

    public TaskResourceReference getResRef() {
        return resRef;
    }

    public void setResRef(TaskResourceReference value) {
        this.resRef = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public SubtaskTrainingLevelDecision.Applic getApplic() {
        return applic;
    }

    public void setApplic(SubtaskTrainingLevelDecision.Applic value) {
        this.applic = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public TaskResourceRelationship() {
		super("http://www.asd-europe.org/s-series/s3000l", "TaskResourceRelationship");
	}

}
