/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:55 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class TaskRevisionWarningCautionNote extends EcRemoteLinkedData {

    protected WarningCautionNoteRef wcnRef;
    protected WarningCautionNote wcnDef;
    protected s3000l.ProductName.Applic applic;
    protected String uid;
    protected CrudCodeValues crud;

    public WarningCautionNoteRef getWcnRef() {
        return wcnRef;
    }

    public void setWcnRef(WarningCautionNoteRef value) {
        this.wcnRef = value;
    }

    public WarningCautionNote getWcnDef() {
        return wcnDef;
    }

    public void setWcnDef(WarningCautionNote value) {
        this.wcnDef = value;
    }

    public s3000l.ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(s3000l.ProductName.Applic value) {
        this.applic = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public TaskRevisionWarningCautionNote() {
		super("http://www.asd-europe.org/s-series/s3000l", "TaskRevisionWarningCautionNote");
	}

}
