/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:55 CDT 2019
 *
 **/

package s3000l;


public enum TaskPersonnelResourceRoleCodeValues {

    MAN_A,
    MAN_B,
    PERF,
    SUP,
    QA;
}
