/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:55 CDT 2019
 *
 **/

package s3000l;


public enum TimeRateUnit {

    MS,
    SEC,
    MIN,
    HR,
    DAY,
    WK,
    MON,
    QR,
    YR;
}
