/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s3000l;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class TradeReference extends EcRemoteLinkedData {

    protected TradeName tradeName;
    protected Object uidRef;

    public TradeName getTradeName() {
        return tradeName;
    }

    public void setTradeName(TradeName value) {
        this.tradeName = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public TradeReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "TradeReference");
	}

}
