/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:03 CDT 2019
 *
 **/

package s3000l;


public enum ValueDeterminationCodeValues {

    ALC,
    CALC,
    CONTR,
    DSG,
    EMP,
    EST,
    MEAS,
    PLAN,
    REQ,
    SET,
    SPEC;
}
