/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:18 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class AllowedProductConfigurationByConfigurationIdentifierReference extends EcRemoteLinkedData {

    protected ProductIdentifier prodId;
    protected ProductVariantIdentifier prodVarId;
    protected AllowedProductConfigurationIdentifier prodConfId;
    protected Object uidRef;

    public ProductIdentifier getProdId() {
        return prodId;
    }

    public void setProdId(ProductIdentifier value) {
        this.prodId = value;
    }

    public ProductVariantIdentifier getProdVarId() {
        return prodVarId;
    }

    public void setProdVarId(ProductVariantIdentifier value) {
        this.prodVarId = value;
    }

    public AllowedProductConfigurationIdentifier getProdConfId() {
        return prodConfId;
    }

    public void setProdConfId(AllowedProductConfigurationIdentifier value) {
        this.prodConfId = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public AllowedProductConfigurationByConfigurationIdentifierReference() {
		super("http://asd-europe.org/", "AllowedProductConfigurationByConfigurationIdentifierReference");
	}

}
