/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:18 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ApplicabilityStatementReference extends EcRemoteLinkedData {

    protected ApplicabilityStatementIdentifier applicId;
    protected Object uidRef;

    public ApplicabilityStatementIdentifier getApplicId() {
        return applicId;
    }

    public void setApplicId(ApplicabilityStatementIdentifier value) {
        this.applicId = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public ApplicabilityStatementReference() {
		super("http://asd-europe.org/", "ApplicabilityStatementReference");
	}

}
