/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:18 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ApplicabilityEvaluationByAssertionOfCondition extends EcRemoteLinkedData {

    protected ConditionTypeReference condTypeRef;
    protected ConditionInstanceReference condInstRef;
    protected ConditionTypeValueReference assertValue;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public ConditionTypeReference getCondTypeRef() {
        return condTypeRef;
    }

    public void setCondTypeRef(ConditionTypeReference value) {
        this.condTypeRef = value;
    }

    public ConditionInstanceReference getCondInstRef() {
        return condInstRef;
    }

    public void setCondInstRef(ConditionInstanceReference value) {
        this.condInstRef = value;
    }

    public ConditionTypeValueReference getAssertValue() {
        return assertValue;
    }

    public void setAssertValue(ConditionTypeValueReference value) {
        this.assertValue = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s6000t.taskTrainAnalysis.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public ApplicabilityEvaluationByAssertionOfCondition() {
		super("http://asd-europe.org/", "ApplicabilityEvaluationByAssertionOfCondition");
	}

}
