/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:18 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ApplicabilityEvaluationByApplicabilityStatementReference extends EcRemoteLinkedData {

    protected ApplicabilityStatementReference applicRef;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public ApplicabilityStatementReference getApplicRef() {
        return applicRef;
    }

    public void setApplicRef(ApplicabilityStatementReference value) {
        this.applicRef = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s6000t.taskTrainAnalysis.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public ApplicabilityEvaluationByApplicabilityStatementReference() {
		super("http://asd-europe.org/", "ApplicabilityEvaluationByApplicabilityStatementReference");
	}

}
