/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class BreakdownElementUsageInBreakdown extends EcRemoteLinkedData {

    protected BreakdownElementRevisionReference beRef;
    protected Array<BreakdownElementStructure> beChild;
    protected BreakdownElementInZoneRelationship inZone;
    protected s6000t.taskTrainAnalysis.HardwareElementPartRealization.UsableOnList usableOnList;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public BreakdownElementRevisionReference getBeRef() {
        return beRef;
    }

    public void setBeRef(BreakdownElementRevisionReference value) {
        this.beRef = value;
    }

    public Array<BreakdownElementStructure> getBeChild() {
        if (beChild == null) {
            beChild = new Array<BreakdownElementStructure>();
        }
        return this.beChild;
    }

    public BreakdownElementInZoneRelationship getInZone() {
        return inZone;
    }

    public void setInZone(BreakdownElementInZoneRelationship value) {
        this.inZone = value;
    }

    public s6000t.taskTrainAnalysis.HardwareElementPartRealization.UsableOnList getUsableOnList() {
        return usableOnList;
    }

    public void setUsableOnList(s6000t.taskTrainAnalysis.HardwareElementPartRealization.UsableOnList value) {
        this.usableOnList = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s6000t.taskTrainAnalysis.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public BreakdownElementUsageInBreakdown() {
		super("http://asd-europe.org/", "BreakdownElementUsageInBreakdown");
	}

}
