/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class CircuitBreakerIdentifier extends EcRemoteLinkedData {

    protected CircuitBreakerIdentifierClassValues clazz;
    protected OrganizationReference setBy;

    public CircuitBreakerIdentifierClassValues getClazz() {
        return clazz;
    }

    public void setClazz(CircuitBreakerIdentifierClassValues value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public CircuitBreakerIdentifier() {
		super("http://asd-europe.org/", "CircuitBreakerIdentifier");
	}

}
