/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ContractedBlockOfSerializedItems extends EcRemoteLinkedData {

    protected String lowBound;
    protected String uppBound;

    public String getLowBound() {
        return lowBound;
    }

    public void setLowBound(String value) {
        this.lowBound = value;
    }

    public String getUppBound() {
        return uppBound;
    }

    public void setUppBound(String value) {
        this.uppBound = value;
    }

	public ContractedBlockOfSerializedItems() {
		super("http://asd-europe.org/", "ContractedBlockOfSerializedItems");
	}

}
