/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ContractRelationship extends EcRemoteLinkedData {

    protected ContractRelationshipType relType;
    protected ContractReference contrRef;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public ContractRelationshipType getRelType() {
        return relType;
    }

    public void setRelType(ContractRelationshipType value) {
        this.relType = value;
    }

    public ContractReference getContrRef() {
        return contrRef;
    }

    public void setContrRef(ContractReference value) {
        this.contrRef = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s6000t.taskTrainAnalysis.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public ContractRelationship() {
		super("http://asd-europe.org/", "ContractRelationship");
	}

}
