/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ContractedProductVariantAtOperatingLocation extends EcRemoteLinkedData {

    protected QuantityOfProductVariantAtOperatingLocation qty;
    protected OperatingRequirementAtOperatingLocation opReq;
    protected OperatingLocationReference theaterOfOp;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public QuantityOfProductVariantAtOperatingLocation getQty() {
        return qty;
    }

    public void setQty(QuantityOfProductVariantAtOperatingLocation value) {
        this.qty = value;
    }

    public OperatingRequirementAtOperatingLocation getOpReq() {
        return opReq;
    }

    public void setOpReq(OperatingRequirementAtOperatingLocation value) {
        this.opReq = value;
    }

    public OperatingLocationReference getTheaterOfOp() {
        return theaterOfOp;
    }

    public void setTheaterOfOp(OperatingLocationReference value) {
        this.theaterOfOp = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s6000t.taskTrainAnalysis.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public ContractedProductVariantAtOperatingLocation() {
		super("http://asd-europe.org/", "ContractedProductVariantAtOperatingLocation");
	}

}
