/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;


public enum CurrencyUnit {

    ARS,
    AUD,
    BRL,
    CAD,
    CHF,
    CNY,
    CZK,
    DKK,
    EUR,
    GBP,
    HKD,
    INR,
    JPY,
    KRW,
    NOK,
    PLN,
    RUB,
    SAR,
    SEK,
    SGD,
    USD,
    ZAR;
}
