/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class DataModuleIssueNumber extends EcRemoteLinkedData {

    protected DataModuleIssueNumberClassValues clazz;
    protected OrganizationReference setBy;

    public DataModuleIssueNumberClassValues getClazz() {
        return clazz;
    }

    public void setClazz(DataModuleIssueNumberClassValues value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public DataModuleIssueNumber() {
		super("http://asd-europe.org/", "DataModuleIssueNumber");
	}

}
