/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class ExternalDocument extends EcRemoteLinkedData {

    protected Array<DocumentIdentifier> docId;
    protected DocumentTitle docTitle;
    protected DocumentType docType;
    protected DocumentLocation docLoc;
    protected Array<ExternalDocumentIssue> docIss;
    protected s6000t.taskTrainAnalysis.DownTime.OrgInfos orgInfos;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public Array<DocumentIdentifier> getDocId() {
        if (docId == null) {
            docId = new Array<DocumentIdentifier>();
        }
        return this.docId;
    }

    public DocumentTitle getDocTitle() {
        return docTitle;
    }

    public void setDocTitle(DocumentTitle value) {
        this.docTitle = value;
    }

    public DocumentType getDocType() {
        return docType;
    }

    public void setDocType(DocumentType value) {
        this.docType = value;
    }

    public DocumentLocation getDocLoc() {
        return docLoc;
    }

    public void setDocLoc(DocumentLocation value) {
        this.docLoc = value;
    }

    public Array<ExternalDocumentIssue> getDocIss() {
        if (docIss == null) {
            docIss = new Array<ExternalDocumentIssue>();
        }
        return this.docIss;
    }

    public s6000t.taskTrainAnalysis.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s6000t.taskTrainAnalysis.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s6000t.taskTrainAnalysis.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public ExternalDocument() {
		super("http://asd-europe.org/", "ExternalDocument");
	}

}
