/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:19 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class FailureModeReference extends EcRemoteLinkedData {

    protected FailureModeIdentifier fmId;
    protected Object uidRef;

    public FailureModeIdentifier getFmId() {
        return fmId;
    }

    public void setFmId(FailureModeIdentifier value) {
        this.fmId = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public FailureModeReference() {
		super("http://asd-europe.org/", "FailureModeReference");
	}

}
