/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:20 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class LearningObjectivePerformanceStandard extends EcRemoteLinkedData {

    protected Array<BehaviorCondition> behvrCond;
    protected Array<BehaviorAction> behvrActn;
    protected Array<BehaviorStandard> behvrStd;

    public Array<BehaviorCondition> getBehvrCond() {
        if (behvrCond == null) {
            behvrCond = new Array<BehaviorCondition>();
        }
        return this.behvrCond;
    }

    public Array<BehaviorAction> getBehvrActn() {
        if (behvrActn == null) {
            behvrActn = new Array<BehaviorAction>();
        }
        return this.behvrActn;
    }

    public Array<BehaviorStandard> getBehvrStd() {
        if (behvrStd == null) {
            behvrStd = new Array<BehaviorStandard>();
        }
        return this.behvrStd;
    }

	public LearningObjectivePerformanceStandard() {
		super("http://asd-europe.org/", "LearningObjectivePerformanceStandard");
	}

}
