/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:20 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class MaintenanceLocationReference extends EcRemoteLinkedData {

    protected MaintenanceLocationIdentifier mLocId;
    protected Object uidRef;

    public MaintenanceLocationIdentifier getMLocId() {
        return mLocId;
    }

    public void setMLocId(MaintenanceLocationIdentifier value) {
        this.mLocId = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public MaintenanceLocationReference() {
		super("http://asd-europe.org/", "MaintenanceLocationReference");
	}

}
