/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:20 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;


public enum MassUnit {

    CG,
    DC,
    DG,
    DM,
    GM,
    HG,
    HW,
    KG,
    LT,
    MG,
    TM,
    OZ,
    QK,
    QN,
    LB,
    TO,
    TN;
}
