/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:20 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Date;

public class MessageCreationDate extends EcRemoteLinkedData {

    protected Date dateTime;

    public Date getDateTime() {
        return dateTime;
    }

    public void setDateTime(Date value) {
        this.dateTime = value;
    }

	public MessageCreationDate() {
		super("http://asd-europe.org/", "MessageCreationDate");
	}

}
