/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:21 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class OrganizationIdentifier extends EcRemoteLinkedData {

    protected OrganizationIdentifierClassValues clazz;
    protected s6000t.taskTrainAnalysis.ProductName.Applic applic;

    public OrganizationIdentifierClassValues getClazz() {
        return clazz;
    }

    public void setClazz(OrganizationIdentifierClassValues value) {
        this.clazz = value;
    }

    public s6000t.taskTrainAnalysis.ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(s6000t.taskTrainAnalysis.ProductName.Applic value) {
        this.applic = value;
    }

	public OrganizationIdentifier() {
		super("http://asd-europe.org/", "OrganizationIdentifier");
	}

}
