/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:21 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class PartsListEntryIdentifier extends EcRemoteLinkedData {

    protected PartsListEntryIdentifierClassValues clazz;
    protected OrganizationReference setBy;

    public PartsListEntryIdentifierClassValues getClazz() {
        return clazz;
    }

    public void setClazz(PartsListEntryIdentifierClassValues value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public PartsListEntryIdentifier() {
		super("http://asd-europe.org/", "PartsListEntryIdentifier");
	}

}
