/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:21 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class ProductIdentifier extends EcRemoteLinkedData {

    protected ProductIdentifierClassValues clazz;
    protected OrganizationReference setBy;

    public ProductIdentifierClassValues getClazz() {
        return clazz;
    }

    public void setClazz(ProductIdentifierClassValues value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public ProductIdentifier() {
		super("http://asd-europe.org/", "ProductIdentifier");
	}

}
