/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:21 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class PublicationModuleCode extends EcRemoteLinkedData {

    protected PublicationModuleCodeClassValues clazz;
    protected OrganizationReference setBy;

    public PublicationModuleCodeClassValues getClazz() {
        return clazz;
    }

    public void setClazz(PublicationModuleCodeClassValues value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public PublicationModuleCode() {
		super("http://asd-europe.org/", "PublicationModuleCode");
	}

}
