/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:21 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class QuantifiedSpecialEventOccurrence extends EcRemoteLinkedData {

    protected Array<SpecialEventOccurrenceRate> occRte;
    protected Array<ProductUsagePhaseReference> usagePhaseRef;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Docs docs;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Rmks rmks;
    protected s6000t.taskTrainAnalysis.ProductName.Applic applic;
    protected String uid;
    protected CrudCodeValues crud;

    public Array<SpecialEventOccurrenceRate> getOccRte() {
        if (occRte == null) {
            occRte = new Array<SpecialEventOccurrenceRate>();
        }
        return this.occRte;
    }

    public Array<ProductUsagePhaseReference> getUsagePhaseRef() {
        if (usagePhaseRef == null) {
            usagePhaseRef = new Array<ProductUsagePhaseReference>();
        }
        return this.usagePhaseRef;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s6000t.taskTrainAnalysis.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s6000t.taskTrainAnalysis.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public s6000t.taskTrainAnalysis.ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(s6000t.taskTrainAnalysis.ProductName.Applic value) {
        this.applic = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public QuantifiedSpecialEventOccurrence() {
		super("http://asd-europe.org/", "QuantifiedSpecialEventOccurrence");
	}

}
