/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:21 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class RepeatTimeLimitReference extends EcRemoteLinkedData {

    protected Object uidRef;

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public RepeatTimeLimitReference() {
		super("http://asd-europe.org/", "RepeatTimeLimitReference");
	}

}
