/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:21 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class S1000DDataModule extends EcRemoteLinkedData {

    protected DataModuleCode dmc;
    protected DataModuleInfoname infoname;
    protected Array<S1000DDataModuleIssue> dmIss;
    protected s6000t.taskTrainAnalysis.DownTime.OrgInfos orgInfos;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public DataModuleCode getDmc() {
        return dmc;
    }

    public void setDmc(DataModuleCode value) {
        this.dmc = value;
    }

    public DataModuleInfoname getInfoname() {
        return infoname;
    }

    public void setInfoname(DataModuleInfoname value) {
        this.infoname = value;
    }

    public Array<S1000DDataModuleIssue> getDmIss() {
        if (dmIss == null) {
            dmIss = new Array<S1000DDataModuleIssue>();
        }
        return this.dmIss;
    }

    public s6000t.taskTrainAnalysis.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s6000t.taskTrainAnalysis.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s6000t.taskTrainAnalysis.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public S1000DDataModule() {
		super("http://asd-europe.org/", "S1000DDataModule");
	}

}
