/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:21 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class SoftwarePartAsDesigned extends EcRemoteLinkedData {

    protected Array<PartIdentifier> partId;
    protected Array<PartName> name;
    protected PartDemilitarizationClass dec;
    protected PartSpecialHandlingRequirement phstReq;
    protected Array<PartMaturityClass> maturity;
    protected Array<PartObsolescenceRiskAssessment> obsRisk;
    protected SoftwareType swType;
    protected SoftwarePartSize swSize;
    protected Array<PartAsDesignedPartsList> partsList;
    protected Array<AlternatePartAsDesignedRelationship> altPart;
    protected s6000t.taskTrainAnalysis.OperationalTask.Secs secs;
    protected LsaCandidateIndicator lsaCand;
    protected LsaCandidateRationale candRtnl;
    protected Array<LsaCandidateMaintenanceConcept> maintCpt;
    protected Array<LsaCandidateMaintenanceSolution> maintSln;
    protected Array<s6000t.taskTrainAnalysis.ZoneElementRevision.SrvLife> productServiceLife;
    protected Array<s6000t.taskTrainAnalysis.ZoneElementRevision.SmInt> scheduledMaintenanceInterval;
    protected Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mfop> maintenanceFreeOperatingPeriod;
    protected Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Dt> downTime;
    protected Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mmhoh> maintenanceManHoursPerOperatingHour;
    protected Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mtbur> meanTimeBetweenUnscheduledRemoval;
    protected Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mttr> meanTimeToRepair;
    protected Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Dmc> directMaintenanceCost;
    protected Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Spt> shopProcessingTime;
    protected Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Foh> failuresPerOperatingHour;
    protected Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Rplt> replacementTime;
    protected Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Lcc> lifeCycleCost;
    protected Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mtbf> meanTimeBetweenFailure;
    protected Array<s6000t.taskTrainAnalysis.ZoneElementRevision.FRate> failureRate;
    protected LsaCandidateAnalysisActivities anlysActvty;
    protected Array<TaskRequirementTarget> taskReq;
    protected Array<Object> taskTargetNonAbstractClasses;
    protected s6000t.taskTrainAnalysis.DownTime.OrgInfos orgInfos;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Docs docs;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Rmks rmks;
    protected s6000t.taskTrainAnalysis.ZoneElementRevision.DmgAnlys dmgAnlys;
    protected s6000t.taskTrainAnalysis.ZoneElementRevision.FailModes failModes;
    protected s6000t.taskTrainAnalysis.ZoneElementRevision.DetectMnCaps detectMnCaps;
    protected String uid;
    protected CrudCodeValues crud;

    public Array<PartIdentifier> getPartId() {
        if (partId == null) {
            partId = new Array<PartIdentifier>();
        }
        return this.partId;
    }

    public Array<PartName> getName() {
        if (name == null) {
            name = new Array<PartName>();
        }
        return this.name;
    }

    public PartDemilitarizationClass getDec() {
        return dec;
    }

    public void setDec(PartDemilitarizationClass value) {
        this.dec = value;
    }

    public PartSpecialHandlingRequirement getPhstReq() {
        return phstReq;
    }

    public void setPhstReq(PartSpecialHandlingRequirement value) {
        this.phstReq = value;
    }

    public Array<PartMaturityClass> getMaturity() {
        if (maturity == null) {
            maturity = new Array<PartMaturityClass>();
        }
        return this.maturity;
    }

    public Array<PartObsolescenceRiskAssessment> getObsRisk() {
        if (obsRisk == null) {
            obsRisk = new Array<PartObsolescenceRiskAssessment>();
        }
        return this.obsRisk;
    }

    public SoftwareType getSwType() {
        return swType;
    }

    public void setSwType(SoftwareType value) {
        this.swType = value;
    }

    public SoftwarePartSize getSwSize() {
        return swSize;
    }

    public void setSwSize(SoftwarePartSize value) {
        this.swSize = value;
    }

    public Array<PartAsDesignedPartsList> getPartsList() {
        if (partsList == null) {
            partsList = new Array<PartAsDesignedPartsList>();
        }
        return this.partsList;
    }

    public Array<AlternatePartAsDesignedRelationship> getAltPart() {
        if (altPart == null) {
            altPart = new Array<AlternatePartAsDesignedRelationship>();
        }
        return this.altPart;
    }

    public s6000t.taskTrainAnalysis.OperationalTask.Secs getSecs() {
        return secs;
    }

    public void setSecs(s6000t.taskTrainAnalysis.OperationalTask.Secs value) {
        this.secs = value;
    }

    public LsaCandidateIndicator getLsaCand() {
        return lsaCand;
    }

    public void setLsaCand(LsaCandidateIndicator value) {
        this.lsaCand = value;
    }

    public LsaCandidateRationale getCandRtnl() {
        return candRtnl;
    }

    public void setCandRtnl(LsaCandidateRationale value) {
        this.candRtnl = value;
    }

    public Array<LsaCandidateMaintenanceConcept> getMaintCpt() {
        if (maintCpt == null) {
            maintCpt = new Array<LsaCandidateMaintenanceConcept>();
        }
        return this.maintCpt;
    }

    public Array<LsaCandidateMaintenanceSolution> getMaintSln() {
        if (maintSln == null) {
            maintSln = new Array<LsaCandidateMaintenanceSolution>();
        }
        return this.maintSln;
    }

    public Array<s6000t.taskTrainAnalysis.ZoneElementRevision.SrvLife> getProductServiceLife() {
        if (productServiceLife == null) {
            productServiceLife = new Array<s6000t.taskTrainAnalysis.ZoneElementRevision.SrvLife>();
        }
        return this.productServiceLife;
    }

    public Array<s6000t.taskTrainAnalysis.ZoneElementRevision.SmInt> getScheduledMaintenanceInterval() {
        if (scheduledMaintenanceInterval == null) {
            scheduledMaintenanceInterval = new Array<s6000t.taskTrainAnalysis.ZoneElementRevision.SmInt>();
        }
        return this.scheduledMaintenanceInterval;
    }

    public Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mfop> getMaintenanceFreeOperatingPeriod() {
        if (maintenanceFreeOperatingPeriod == null) {
            maintenanceFreeOperatingPeriod = new Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mfop>();
        }
        return this.maintenanceFreeOperatingPeriod;
    }

    public Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Dt> getDownTime() {
        if (downTime == null) {
            downTime = new Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Dt>();
        }
        return this.downTime;
    }

    public Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mmhoh> getMaintenanceManHoursPerOperatingHour() {
        if (maintenanceManHoursPerOperatingHour == null) {
            maintenanceManHoursPerOperatingHour = new Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mmhoh>();
        }
        return this.maintenanceManHoursPerOperatingHour;
    }

    public Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mtbur> getMeanTimeBetweenUnscheduledRemoval() {
        if (meanTimeBetweenUnscheduledRemoval == null) {
            meanTimeBetweenUnscheduledRemoval = new Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mtbur>();
        }
        return this.meanTimeBetweenUnscheduledRemoval;
    }

    public Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mttr> getMeanTimeToRepair() {
        if (meanTimeToRepair == null) {
            meanTimeToRepair = new Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mttr>();
        }
        return this.meanTimeToRepair;
    }

    public Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Dmc> getDirectMaintenanceCost() {
        if (directMaintenanceCost == null) {
            directMaintenanceCost = new Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Dmc>();
        }
        return this.directMaintenanceCost;
    }

    public Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Spt> getShopProcessingTime() {
        if (shopProcessingTime == null) {
            shopProcessingTime = new Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Spt>();
        }
        return this.shopProcessingTime;
    }

    public Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Foh> getFailuresPerOperatingHour() {
        if (failuresPerOperatingHour == null) {
            failuresPerOperatingHour = new Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Foh>();
        }
        return this.failuresPerOperatingHour;
    }

    public Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Rplt> getReplacementTime() {
        if (replacementTime == null) {
            replacementTime = new Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Rplt>();
        }
        return this.replacementTime;
    }

    public Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Lcc> getLifeCycleCost() {
        if (lifeCycleCost == null) {
            lifeCycleCost = new Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Lcc>();
        }
        return this.lifeCycleCost;
    }

    public Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mtbf> getMeanTimeBetweenFailure() {
        if (meanTimeBetweenFailure == null) {
            meanTimeBetweenFailure = new Array<s6000t.taskTrainAnalysis.ZoneElementRevision.Mtbf>();
        }
        return this.meanTimeBetweenFailure;
    }

    public Array<s6000t.taskTrainAnalysis.ZoneElementRevision.FRate> getFailureRate() {
        if (failureRate == null) {
            failureRate = new Array<s6000t.taskTrainAnalysis.ZoneElementRevision.FRate>();
        }
        return this.failureRate;
    }

    public LsaCandidateAnalysisActivities getAnlysActvty() {
        return anlysActvty;
    }

    public void setAnlysActvty(LsaCandidateAnalysisActivities value) {
        this.anlysActvty = value;
    }

    public Array<TaskRequirementTarget> getTaskReq() {
        if (taskReq == null) {
            taskReq = new Array<TaskRequirementTarget>();
        }
        return this.taskReq;
    }

    public Array<Object> getTaskTargetNonAbstractClasses() {
        if (taskTargetNonAbstractClasses == null) {
            taskTargetNonAbstractClasses = new Array<Object>();
        }
        return this.taskTargetNonAbstractClasses;
    }

    public s6000t.taskTrainAnalysis.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s6000t.taskTrainAnalysis.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s6000t.taskTrainAnalysis.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s6000t.taskTrainAnalysis.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public s6000t.taskTrainAnalysis.ZoneElementRevision.DmgAnlys getDmgAnlys() {
        return dmgAnlys;
    }

    public void setDmgAnlys(s6000t.taskTrainAnalysis.ZoneElementRevision.DmgAnlys value) {
        this.dmgAnlys = value;
    }

    public s6000t.taskTrainAnalysis.ZoneElementRevision.FailModes getFailModes() {
        return failModes;
    }

    public void setFailModes(s6000t.taskTrainAnalysis.ZoneElementRevision.FailModes value) {
        this.failModes = value;
    }

    public s6000t.taskTrainAnalysis.ZoneElementRevision.DetectMnCaps getDetectMnCaps() {
        return detectMnCaps;
    }

    public void setDetectMnCaps(s6000t.taskTrainAnalysis.ZoneElementRevision.DetectMnCaps value) {
        this.detectMnCaps = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public SoftwarePartAsDesigned() {
		super("http://asd-europe.org/", "SoftwarePartAsDesigned");
	}

}
