/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class SubsequentRepeatRelationship extends EcRemoteLinkedData {

    protected Array<SubsequentRepeatRelationship.Trig> trig;
    protected RepeatTimeLimitReference repeatRef;
    protected String uid;
    protected CrudCodeValues crud;

    public Array<SubsequentRepeatRelationship.Trig> getTrig() {
        if (trig == null) {
            trig = new Array<SubsequentRepeatRelationship.Trig>();
        }
        return this.trig;
    }

    public RepeatTimeLimitReference getRepeatRef() {
        return repeatRef;
    }

    public void setRepeatRef(RepeatTimeLimitReference value) {
        this.repeatRef = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

    public static class Trig {

        protected ParameterThresholdDefinition paramThld;
        protected TaskThresholdDefinition taskThld;
        protected SpecialEventThresholdDefinition sEvntThld;
        protected FailureModeThresholdDefinition fmThld;

        public ParameterThresholdDefinition getParamThld() {
            return paramThld;
        }

        public void setParamThld(ParameterThresholdDefinition value) {
            this.paramThld = value;
        }

        public TaskThresholdDefinition getTaskThld() {
            return taskThld;
        }

        public void setTaskThld(TaskThresholdDefinition value) {
            this.taskThld = value;
        }

        public SpecialEventThresholdDefinition getSEvntThld() {
            return sEvntThld;
        }

        public void setSEvntThld(SpecialEventThresholdDefinition value) {
            this.sEvntThld = value;
        }

        public FailureModeThresholdDefinition getFmThld() {
            return fmThld;
        }

        public void setFmThld(FailureModeThresholdDefinition value) {
            this.fmThld = value;
        }

    }

	public SubsequentRepeatRelationship() {
		super("http://asd-europe.org/", "SubsequentRepeatRelationship");
	}

}
