/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class SubtaskByTaskReference extends EcRemoteLinkedData {

    protected SubtaskIdentifier subtId;
    protected SubtaskRole subtRole;
    protected Array<SubtaskWarningCautionNote> wcn;
    protected SubtaskTimeline precSubt;
    protected TaskRef taskRef;
    protected s6000t.taskTrainAnalysis.OperationalTask.Secs secs;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Docs docs;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Rmks rmks;
    protected s6000t.taskTrainAnalysis.ProductName.Applic applic;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public SubtaskIdentifier getSubtId() {
        return subtId;
    }

    public void setSubtId(SubtaskIdentifier value) {
        this.subtId = value;
    }

    public SubtaskRole getSubtRole() {
        return subtRole;
    }

    public void setSubtRole(SubtaskRole value) {
        this.subtRole = value;
    }

    public Array<SubtaskWarningCautionNote> getWcn() {
        if (wcn == null) {
            wcn = new Array<SubtaskWarningCautionNote>();
        }
        return this.wcn;
    }

    public SubtaskTimeline getPrecSubt() {
        return precSubt;
    }

    public void setPrecSubt(SubtaskTimeline value) {
        this.precSubt = value;
    }

    public TaskRef getTaskRef() {
        return taskRef;
    }

    public void setTaskRef(TaskRef value) {
        this.taskRef = value;
    }

    public s6000t.taskTrainAnalysis.OperationalTask.Secs getSecs() {
        return secs;
    }

    public void setSecs(s6000t.taskTrainAnalysis.OperationalTask.Secs value) {
        this.secs = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s6000t.taskTrainAnalysis.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s6000t.taskTrainAnalysis.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public s6000t.taskTrainAnalysis.ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(s6000t.taskTrainAnalysis.ProductName.Applic value) {
        this.applic = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public SubtaskByTaskReference() {
		super("http://asd-europe.org/", "SubtaskByTaskReference");
	}

}
