/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class SubtaskTrainDecisionDefinition extends EcRemoteLinkedData {

    protected SubtaskTrainIdentifier subtTrainId;
    protected SubtaskTrainDecision trainDecision;
    protected Array<SubtaskTrainDecisionRationale> trainRtnle;
    protected Array<SubtaskTrainDecisionChangeDescription> trainDecisionChgDescr;
    protected Array<SubtaskPerformanceObjective> perfObj;
    protected Array<Object> subtaskTrainStepNonAbstractClasses;
    protected SubtaskRef subtRef;
    protected s6000t.taskTrainAnalysis.DownTime.OrgInfos orgInfos;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Docs docs;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Rmks rmks;
    protected SubtaskTrainStepDefinition.LevOfLearn levOfLearn;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public SubtaskTrainIdentifier getSubtTrainId() {
        return subtTrainId;
    }

    public void setSubtTrainId(SubtaskTrainIdentifier value) {
        this.subtTrainId = value;
    }

    public SubtaskTrainDecision getTrainDecision() {
        return trainDecision;
    }

    public void setTrainDecision(SubtaskTrainDecision value) {
        this.trainDecision = value;
    }

    public Array<SubtaskTrainDecisionRationale> getTrainRtnle() {
        if (trainRtnle == null) {
            trainRtnle = new Array<SubtaskTrainDecisionRationale>();
        }
        return this.trainRtnle;
    }

    public Array<SubtaskTrainDecisionChangeDescription> getTrainDecisionChgDescr() {
        if (trainDecisionChgDescr == null) {
            trainDecisionChgDescr = new Array<SubtaskTrainDecisionChangeDescription>();
        }
        return this.trainDecisionChgDescr;
    }

    public Array<SubtaskPerformanceObjective> getPerfObj() {
        if (perfObj == null) {
            perfObj = new Array<SubtaskPerformanceObjective>();
        }
        return this.perfObj;
    }

    public Array<Object> getSubtaskTrainStepNonAbstractClasses() {
        if (subtaskTrainStepNonAbstractClasses == null) {
            subtaskTrainStepNonAbstractClasses = new Array<Object>();
        }
        return this.subtaskTrainStepNonAbstractClasses;
    }

    public SubtaskRef getSubtRef() {
        return subtRef;
    }

    public void setSubtRef(SubtaskRef value) {
        this.subtRef = value;
    }

    public s6000t.taskTrainAnalysis.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s6000t.taskTrainAnalysis.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s6000t.taskTrainAnalysis.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s6000t.taskTrainAnalysis.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public SubtaskTrainStepDefinition.LevOfLearn getLevOfLearn() {
        return levOfLearn;
    }

    public void setLevOfLearn(SubtaskTrainStepDefinition.LevOfLearn value) {
        this.levOfLearn = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public SubtaskTrainDecisionDefinition() {
		super("http://asd-europe.org/", "SubtaskTrainDecisionDefinition");
	}

}
