/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class SubtaskTimeline extends EcRemoteLinkedData {

    protected SubtaskTimelineEvent evnt;
    protected Array<SubtaskTimelineLag> lag;
    protected SubtaskRef subtRef;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Docs docs;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Rmks rmks;
    protected s6000t.taskTrainAnalysis.ProductName.Applic applic;
    protected String uid;
    protected CrudCodeValues crud;

    public SubtaskTimelineEvent getEvnt() {
        return evnt;
    }

    public void setEvnt(SubtaskTimelineEvent value) {
        this.evnt = value;
    }

    public Array<SubtaskTimelineLag> getLag() {
        if (lag == null) {
            lag = new Array<SubtaskTimelineLag>();
        }
        return this.lag;
    }

    public SubtaskRef getSubtRef() {
        return subtRef;
    }

    public void setSubtRef(SubtaskRef value) {
        this.subtRef = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s6000t.taskTrainAnalysis.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s6000t.taskTrainAnalysis.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public s6000t.taskTrainAnalysis.ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(s6000t.taskTrainAnalysis.ProductName.Applic value) {
        this.applic = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public SubtaskTimeline() {
		super("http://asd-europe.org/", "SubtaskTimeline");
	}

}
