/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class TaskRequirementAuthority extends EcRemoteLinkedData {

    protected OrganizationReference orgRef;

    public OrganizationReference getOrgRef() {
        return orgRef;
    }

    public void setOrgRef(OrganizationReference value) {
        this.orgRef = value;
    }

	public TaskRequirementAuthority() {
		super("http://asd-europe.org/", "TaskRequirementAuthority");
	}

}
