/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;


public enum TaskPersonnelResourceRoleCodeValues {

    MAN_A,
    MAN_B,
    PERF,
    SUP,
    QA;
}
