/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class TaskIdentifier extends EcRemoteLinkedData {

    protected TaskIdentifierClassValues clazz;
    protected OrganizationReference setBy;

    public TaskIdentifierClassValues getClazz() {
        return clazz;
    }

    public void setClazz(TaskIdentifierClassValues value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public TaskIdentifier() {
		super("http://asd-europe.org/", "TaskIdentifier");
	}

}
