/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class TaskRequirementJustification extends EcRemoteLinkedData {

    protected SpecialEventReference sEvntRef;
    protected FailureModeReference fmRef;
    protected DamageReference dmgRef;
    protected CandidateItemAnalysisActivityReference analysisRef;
    protected FunctionalFailureReference funcFailRef;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Docs docs;
    protected s6000t.taskTrainAnalysis.ConditionInstance.Rmks rmks;
    protected String uid;
    protected CrudCodeValues crud;

    public SpecialEventReference getSEvntRef() {
        return sEvntRef;
    }

    public void setSEvntRef(SpecialEventReference value) {
        this.sEvntRef = value;
    }

    public FailureModeReference getFmRef() {
        return fmRef;
    }

    public void setFmRef(FailureModeReference value) {
        this.fmRef = value;
    }

    public DamageReference getDmgRef() {
        return dmgRef;
    }

    public void setDmgRef(DamageReference value) {
        this.dmgRef = value;
    }

    public CandidateItemAnalysisActivityReference getAnalysisRef() {
        return analysisRef;
    }

    public void setAnalysisRef(CandidateItemAnalysisActivityReference value) {
        this.analysisRef = value;
    }

    public FunctionalFailureReference getFuncFailRef() {
        return funcFailRef;
    }

    public void setFuncFailRef(FunctionalFailureReference value) {
        this.funcFailRef = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s6000t.taskTrainAnalysis.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s6000t.taskTrainAnalysis.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s6000t.taskTrainAnalysis.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public TaskRequirementJustification() {
		super("http://asd-europe.org/", "TaskRequirementJustification");
	}

}
