/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;


public enum TimeRateUnit {

    MS,
    SEC,
    MIN,
    HR,
    DAY,
    WK,
    MON,
    QR,
    YR;
}
