/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:23 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;


public enum VolumeRateUnit {

    BF,
    CL,
    CC,
    CV,
    CF,
    CZ,
    CD,
    DB,
    DL,
    FZ,
    GC,
    HL,
    HC,
    GI,
    PB,
    QB,
    LI,
    ML,
    MC,
    TL,
    GL,
    PT,
    QT;
}
