/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:23 CDT 2019
 *
 **/

package s6000t.taskTrainAnalysis;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class WarningCautionTrainDecisionIterationIdentifier extends EcRemoteLinkedData {

    protected String clazz;
    protected OrganizationReference setBy;

    public String getClazz() {
        return clazz;
    }

    public void setClazz(String value) {
        this.clazz = value;
    }

    public OrganizationReference getSetBy() {
        return setBy;
    }

    public void setSetBy(OrganizationReference value) {
        this.setBy = value;
    }

	public WarningCautionTrainDecisionIterationIdentifier() {
		super("http://asd-europe.org/", "WarningCautionTrainDecisionIterationIdentifier");
	}

}
