/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:18 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import s3000l.ConditionInstance;
import s3000l.ProductName;
import s3000l.TaskImportanceCategoryCodeValues;

public class AlgorithmTaskImportanceCategory extends EcRemoteLinkedData {

    protected TaskImportanceCategoryCodeValues code;
    protected ProductName.Applic applic;
    protected ConditionInstance.Docs docs;
    protected ConditionInstance.Rmks rmks;

    public TaskImportanceCategoryCodeValues getCode() {
        return code;
    }

    public void setCode(TaskImportanceCategoryCodeValues value) {
        this.code = value;
    }

    public ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(ProductName.Applic value) {
        this.applic = value;
    }

    public ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(ConditionInstance.Docs value) {
        this.docs = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

	public AlgorithmTaskImportanceCategory() {
		super("http://www.asd-europe.org/s-series/s6000t", "AlgorithmTaskImportanceCategory");
	}

}
