/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:01 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s3000l.CrudCodeValues;

public class JobPosition extends EcRemoteLinkedData {

    protected Array<JobPositionName> jobPosName;
    protected Array<JobPositionDescription> jobPosDescr;
    protected TrainingPopulationItem trainPopDef;
    protected KnowledgeSkillAttitudeGapAnalysisItem ksaGaps;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public Array<JobPositionName> getJobPosName() {
        if (jobPosName == null) {
            jobPosName = new Array<JobPositionName>();
        }
        return this.jobPosName;
    }

    public Array<JobPositionDescription> getJobPosDescr() {
        if (jobPosDescr == null) {
            jobPosDescr = new Array<JobPositionDescription>();
        }
        return this.jobPosDescr;
    }

    public TrainingPopulationItem getTrainPopDef() {
        return trainPopDef;
    }

    public void setTrainPopDef(TrainingPopulationItem value) {
        this.trainPopDef = value;
    }

    public KnowledgeSkillAttitudeGapAnalysisItem getKsaGaps() {
        return ksaGaps;
    }

    public void setKsaGaps(KnowledgeSkillAttitudeGapAnalysisItem value) {
        this.ksaGaps = value;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public JobPosition() {
		super("http://www.asd-europe.org/s-series/s3000l", "JobPosition");
	}

}
