/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:53 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s6000t.TaskLevelOfLearningLearningObjective;

public class KnowledgeSkillAttitudeLearningObjectiveItem extends EcRemoteLinkedData {

    protected Array<TaskLevelOfLearningLearningObjective> lolLearnObj;

    public Array<TaskLevelOfLearningLearningObjective> getLolLearnObj() {
        if (lolLearnObj == null) {
            lolLearnObj = new Array<TaskLevelOfLearningLearningObjective>();
        }
        return this.lolLearnObj;
    }

	public KnowledgeSkillAttitudeLearningObjectiveItem() {
		super("http://www.asd-europe.org/s-series/s6000t", "KnowledgeSkillAttitudeLearningObjectiveItem");
	}

}
