/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:01 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class KnowledgeSkillAttitudeGapAnalysisItem extends EcRemoteLinkedData {

    protected Array<KnowledgeSkillAttitudeGapDefinition> ksaGap;

    public Array<KnowledgeSkillAttitudeGapDefinition> getKsaGap() {
        if (ksaGap == null) {
            ksaGap = new Array<KnowledgeSkillAttitudeGapDefinition>();
        }
        return this.ksaGap;
    }

	public KnowledgeSkillAttitudeGapAnalysisItem() {
		super("http://www.asd-europe.org/s-series/s3000l", "KnowledgeSkillAttitudeGapAnalysisItem");
	}

}
