/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:01 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s3000l.CrudCodeValues;

public class KnowledgeSkillAttitudeGapDefinition extends EcRemoteLinkedData {

    protected KnowledgeSkillAttitudeGapIdentifier gapId;
    protected Array<KnowledgeSkillAttitudeGapDefinitionIteration> gapIter;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public KnowledgeSkillAttitudeGapIdentifier getGapId() {
        return gapId;
    }

    public void setGapId(KnowledgeSkillAttitudeGapIdentifier value) {
        this.gapId = value;
    }

    public Array<KnowledgeSkillAttitudeGapDefinitionIteration> getGapIter() {
        if (gapIter == null) {
            gapIter = new Array<KnowledgeSkillAttitudeGapDefinitionIteration>();
        }
        return this.gapIter;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public KnowledgeSkillAttitudeGapDefinition() {
		super("http://www.asd-europe.org/s-series/s3000l", "KnowledgeSkillAttitudeGapDefinition");
	}

}
