/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:01 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s3000l.*;

public class LearningObjectiveTrainingComponent extends EcRemoteLinkedData {

    protected TrainingComponentSequenceNumber compSeqNr;
    protected Array<TrainingComponentName> compName;
    protected TrainingComponentMedia media;
    protected TrainingComponentMethod method;
    protected Array<TrainingComponentSpecialResourceRequirement> resRqmt;
    protected Array<TrainingComponentLearningObjectiveDependency> loDepend;
    protected LearningAssessmentItem assessmnts;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public TrainingComponentSequenceNumber getCompSeqNr() {
        return compSeqNr;
    }

    public void setCompSeqNr(TrainingComponentSequenceNumber value) {
        this.compSeqNr = value;
    }

    public Array<TrainingComponentName> getCompName() {
        if (compName == null) {
            compName = new Array<TrainingComponentName>();
        }
        return this.compName;
    }

    public TrainingComponentMedia getMedia() {
        return media;
    }

    public void setMedia(TrainingComponentMedia value) {
        this.media = value;
    }

    public TrainingComponentMethod getMethod() {
        return method;
    }

    public void setMethod(TrainingComponentMethod value) {
        this.method = value;
    }

    public Array<TrainingComponentSpecialResourceRequirement> getResRqmt() {
        if (resRqmt == null) {
            resRqmt = new Array<TrainingComponentSpecialResourceRequirement>();
        }
        return this.resRqmt;
    }

    public Array<TrainingComponentLearningObjectiveDependency> getLoDepend() {
        if (loDepend == null) {
            loDepend = new Array<TrainingComponentLearningObjectiveDependency>();
        }
        return this.loDepend;
    }

    public LearningAssessmentItem getAssessmnts() {
        return assessmnts;
    }

    public void setAssessmnts(LearningAssessmentItem value) {
        this.assessmnts = value;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public LearningObjectiveTrainingComponent() {
		super("http://www.asd-europe.org/s-series/s3000l", "LearningObjectiveTrainingComponent");
	}

}
