/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:01 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s3000l.CrudCodeValues;

public class LearningObjectiveRevision extends EcRemoteLinkedData {

    protected LearningObjectiveRevisionIdentifier loRevId;
    protected Array<LearningObjectiveRevisionRationale> loRevRtnle;
    protected Array<LearningObjectiveDescription> loDescr;
    protected Array<LearningObjectivePerformanceStandard> loPerfStd;
    protected Array<LearningObjectiveTrainingStrategy> loTrainStrat;
    protected Array<LearningObjectiveRelationship> relLO;
    protected LearningAssessmentItem assessmnts;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public LearningObjectiveRevisionIdentifier getLoRevId() {
        return loRevId;
    }

    public void setLoRevId(LearningObjectiveRevisionIdentifier value) {
        this.loRevId = value;
    }

    public Array<LearningObjectiveRevisionRationale> getLoRevRtnle() {
        if (loRevRtnle == null) {
            loRevRtnle = new Array<LearningObjectiveRevisionRationale>();
        }
        return this.loRevRtnle;
    }

    public Array<LearningObjectiveDescription> getLoDescr() {
        if (loDescr == null) {
            loDescr = new Array<LearningObjectiveDescription>();
        }
        return this.loDescr;
    }

    public Array<LearningObjectivePerformanceStandard> getLoPerfStd() {
        if (loPerfStd == null) {
            loPerfStd = new Array<LearningObjectivePerformanceStandard>();
        }
        return this.loPerfStd;
    }

    public Array<LearningObjectiveTrainingStrategy> getLoTrainStrat() {
        if (loTrainStrat == null) {
            loTrainStrat = new Array<LearningObjectiveTrainingStrategy>();
        }
        return this.loTrainStrat;
    }

    public Array<LearningObjectiveRelationship> getRelLO() {
        if (relLO == null) {
            relLO = new Array<LearningObjectiveRelationship>();
        }
        return this.relLO;
    }

    public LearningAssessmentItem getAssessmnts() {
        return assessmnts;
    }

    public void setAssessmnts(LearningAssessmentItem value) {
        this.assessmnts = value;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public LearningObjectiveRevision() {
		super("http://www.asd-europe.org/s-series/s3000l", "LearningObjectiveRevision");
	}

}
