/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:01 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class LearningObjectiveAssessment extends EcRemoteLinkedData {

	public LearningObjectiveAssessment() {
		super("http://www.asd-europe.org/s-series/s3000l", "LearningObjectiveAssessment");
	}

}
