/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:53 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class LearningObjectiveAssessment extends EcRemoteLinkedData {

	public LearningObjectiveAssessment() {
		super("http://www.asd-europe.org/s-series/s6000t", "LearningObjectiveAssessment");
	}

}
