/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:20 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class LevelOfLearningLearningObjectiveSequenceNumber extends EcRemoteLinkedData {

    protected int value;

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
    }

	public LevelOfLearningLearningObjectiveSequenceNumber() {
		super("http://www.asd-europe.org/s-series/s6000t", "LevelOfLearningLearningObjectiveSequenceNumber");
	}

}
