/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:03 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import s3000l.LanguageCodeValues;
import s3000l.OrganizationReference;

public class SubtaskTrainStepName extends EcRemoteLinkedData {

    protected String name;
    protected LanguageCodeValues lang;
    protected OrganizationReference providedBy;

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public LanguageCodeValues getLang() {
        return lang;
    }

    public void setLang(LanguageCodeValues value) {
        this.lang = value;
    }

    public OrganizationReference getProvidedBy() {
        return providedBy;
    }

    public void setProvidedBy(OrganizationReference value) {
        this.providedBy = value;
    }

	public SubtaskTrainStepName() {
		super("http://www.asd-europe.org/s-series/s3000l", "SubtaskTrainStepName");
	}

}
