/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import s3000l.TaskIdentifier;
import s3000l.TaskRevisionIdentifier;

public class SubtaskTrainDecisionDefinitionRef extends EcRemoteLinkedData {

    protected TaskIdentifier taskId;
    protected TaskRevisionIdentifier taskRevId;
    protected TaskTrainDecisionIterationIdentifier iterationId;
    protected SubtaskTrainIdentifier subtTrainId;
    protected Object uidRef;
    protected String uriRef;

    public TaskIdentifier getTaskId() {
        return taskId;
    }

    public void setTaskId(TaskIdentifier value) {
        this.taskId = value;
    }

    public TaskRevisionIdentifier getTaskRevId() {
        return taskRevId;
    }

    public void setTaskRevId(TaskRevisionIdentifier value) {
        this.taskRevId = value;
    }

    public TaskTrainDecisionIterationIdentifier getIterationId() {
        return iterationId;
    }

    public void setIterationId(TaskTrainDecisionIterationIdentifier value) {
        this.iterationId = value;
    }

    public SubtaskTrainIdentifier getSubtTrainId() {
        return subtTrainId;
    }

    public void setSubtTrainId(SubtaskTrainIdentifier value) {
        this.subtTrainId = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

    public String getUriRef() {
        return uriRef;
    }

    public void setUriRef(String value) {
        this.uriRef = value;
    }

	public SubtaskTrainDecisionDefinitionRef() {
		super("http://www.asd-europe.org/s-series/s3000l", "SubtaskTrainDecisionDefinitionRef");
	}

}
