/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:02 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class SubtaskStepPerformanceStandard extends EcRemoteLinkedData {

    protected Array<SubtaskStepBehaviorCondition> cond;
    protected Array<SubtaskStepBehaviorAction> action;
    protected Array<SubtaskStepBehaviorStandard> std;
    protected Array<SubtaskStepPerformanceStandardStatement> poStmnt;
    protected SubtaskTrainingLevelDecision.Applic applic;

    public Array<SubtaskStepBehaviorCondition> getCond() {
        if (cond == null) {
            cond = new Array<SubtaskStepBehaviorCondition>();
        }
        return this.cond;
    }

    public Array<SubtaskStepBehaviorAction> getAction() {
        if (action == null) {
            action = new Array<SubtaskStepBehaviorAction>();
        }
        return this.action;
    }

    public Array<SubtaskStepBehaviorStandard> getStd() {
        if (std == null) {
            std = new Array<SubtaskStepBehaviorStandard>();
        }
        return this.std;
    }

    public Array<SubtaskStepPerformanceStandardStatement> getPoStmnt() {
        if (poStmnt == null) {
            poStmnt = new Array<SubtaskStepPerformanceStandardStatement>();
        }
        return this.poStmnt;
    }

    public SubtaskTrainingLevelDecision.Applic getApplic() {
        return applic;
    }

    public void setApplic(SubtaskTrainingLevelDecision.Applic value) {
        this.applic = value;
    }

	public SubtaskStepPerformanceStandard() {
		super("http://www.asd-europe.org/s-series/s3000l", "SubtaskStepPerformanceStandard");
	}

}
