/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:55 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class SubtaskPerformanceObjective extends EcRemoteLinkedData {

    protected Array<SubtaskBehaviorCondition> behvrCond;
    protected Array<SubtaskBehaviorAction> behvrActn;
    protected Array<SubtaskBehaviorStandard> behvrStd;
    protected s3000l.ProductName.Applic applic;

    public Array<SubtaskBehaviorCondition> getBehvrCond() {
        if (behvrCond == null) {
            behvrCond = new Array<SubtaskBehaviorCondition>();
        }
        return this.behvrCond;
    }

    public Array<SubtaskBehaviorAction> getBehvrActn() {
        if (behvrActn == null) {
            behvrActn = new Array<SubtaskBehaviorAction>();
        }
        return this.behvrActn;
    }

    public Array<SubtaskBehaviorStandard> getBehvrStd() {
        if (behvrStd == null) {
            behvrStd = new Array<SubtaskBehaviorStandard>();
        }
        return this.behvrStd;
    }

    public s3000l.ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(s3000l.ProductName.Applic value) {
        this.applic = value;
    }

	public SubtaskPerformanceObjective() {
		super("http://www.asd-europe.org/s-series/s6000t", "SubtaskPerformanceObjective");
	}

}
