/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import s3000l.TaskIdentifier;
import s3000l.TaskRevisionIdentifier;
import s6000t.SubtaskTrainIdentifier;
import s6000t.SubtaskTrainStepIdentifier;
import s6000t.TaskTrainDecisionIterationIdentifier;

public class SubtaskTrainStepDefinitionRef extends EcRemoteLinkedData {

    protected TaskIdentifier taskId;
    protected TaskRevisionIdentifier taskRevId;
    protected TaskTrainDecisionIterationIdentifier trainIterationId;
    protected SubtaskTrainIdentifier subtTrainId;
    protected SubtaskTrainStepIdentifier stepId;
    protected Object uidRef;

    public TaskIdentifier getTaskId() {
        return taskId;
    }

    public void setTaskId(TaskIdentifier value) {
        this.taskId = value;
    }

    public TaskRevisionIdentifier getTaskRevId() {
        return taskRevId;
    }

    public void setTaskRevId(TaskRevisionIdentifier value) {
        this.taskRevId = value;
    }

    public TaskTrainDecisionIterationIdentifier getTrainIterationId() {
        return trainIterationId;
    }

    public void setTrainIterationId(TaskTrainDecisionIterationIdentifier value) {
        this.trainIterationId = value;
    }

    public SubtaskTrainIdentifier getSubtTrainId() {
        return subtTrainId;
    }

    public void setSubtTrainId(SubtaskTrainIdentifier value) {
        this.subtTrainId = value;
    }

    public SubtaskTrainStepIdentifier getStepId() {
        return stepId;
    }

    public void setStepId(SubtaskTrainStepIdentifier value) {
        this.stepId = value;
    }

    public Object getUidRef() {
        return uidRef;
    }

    public void setUidRef(Object value) {
        this.uidRef = value;
    }

	public SubtaskTrainStepDefinitionRef() {
		super("http://www.asd-europe.org/s-series/s6000t", "SubtaskTrainStepDefinitionRef");
	}

}
