/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:55 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class SubtaskStepPerformanceStandard extends EcRemoteLinkedData {

    protected Array<SubtaskStepBehaviorCondition> behvrCond;
    protected Array<SubtaskStepBehaviorAction> behvrActn;
    protected Array<SubtaskStepBehaviorStandard> behvrStd;
    protected s3000l.ProductName.Applic applic;

    public Array<SubtaskStepBehaviorCondition> getBehvrCond() {
        if (behvrCond == null) {
            behvrCond = new Array<SubtaskStepBehaviorCondition>();
        }
        return this.behvrCond;
    }

    public Array<SubtaskStepBehaviorAction> getBehvrActn() {
        if (behvrActn == null) {
            behvrActn = new Array<SubtaskStepBehaviorAction>();
        }
        return this.behvrActn;
    }

    public Array<SubtaskStepBehaviorStandard> getBehvrStd() {
        if (behvrStd == null) {
            behvrStd = new Array<SubtaskStepBehaviorStandard>();
        }
        return this.behvrStd;
    }

    public s3000l.ProductName.Applic getApplic() {
        return applic;
    }

    public void setApplic(s3000l.ProductName.Applic value) {
        this.applic = value;
    }

	public SubtaskStepPerformanceStandard() {
		super("http://www.asd-europe.org/s-series/s6000t", "SubtaskStepPerformanceStandard");
	}

}
