/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:03 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import s3000l.CrudCodeValues;

public class TaskPsychomotorLevelOfLearning extends EcRemoteLinkedData {

    protected TaskPsychomotorLevelOfLearningIterationIdentifier psychoIterId;
    protected PsychomotorLevelOfLearning psychoLoL;
    protected TaskLevelOfLearningCharacteristics taskLoLChar;
    protected TaskKnowledgeSkillAttitudeGapItem taskKSAGaps;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public TaskPsychomotorLevelOfLearningIterationIdentifier getPsychoIterId() {
        return psychoIterId;
    }

    public void setPsychoIterId(TaskPsychomotorLevelOfLearningIterationIdentifier value) {
        this.psychoIterId = value;
    }

    public PsychomotorLevelOfLearning getPsychoLoL() {
        return psychoLoL;
    }

    public void setPsychoLoL(PsychomotorLevelOfLearning value) {
        this.psychoLoL = value;
    }

    public TaskLevelOfLearningCharacteristics getTaskLoLChar() {
        return taskLoLChar;
    }

    public void setTaskLoLChar(TaskLevelOfLearningCharacteristics value) {
        this.taskLoLChar = value;
    }

    public TaskKnowledgeSkillAttitudeGapItem getTaskKSAGaps() {
        return taskKSAGaps;
    }

    public void setTaskKSAGaps(TaskKnowledgeSkillAttitudeGapItem value) {
        this.taskKSAGaps = value;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public TaskPsychomotorLevelOfLearning() {
		super("http://www.asd-europe.org/s-series/s3000l", "TaskPsychomotorLevelOfLearning");
	}

}
