/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:22 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s3000l.*;

public class TaskTrainDecisionByEvaluation extends EcRemoteLinkedData {

    protected TaskTrainDecisionIterationIdentifier iterationId;
    protected Array<TaskTrainDecisionRationale> dcsnRtnle;
    protected Array<TaskTrainDecisionIterationRationale> iterRtnle;
    protected TaskTrainDecisionIterationDate iterDate;
    protected TaskTargetAudience audience;
    protected TaskHumanInteractionRequirement coordCat;
    protected TaskDifficultyCategory taskDiff;
    protected TaskImportanceCategory taskImp;
    protected TaskFrequencyCategory taskFreq;
    protected TaskTrainLevel trainLev;
    protected Array<TaskTrainLevelRationale> trainLevRtnle;
    protected TaskTrainingDifficulty trainDiff;
    protected TaskTrainingDecision trainTask;
    protected Array<TaskTrainingDecisionRationale> trainRtnle;
    protected Array<TaskPerformanceObjective> perfObj;
    protected AlgorithmDerivedTaskTrainLevel algTrainLev;
    protected Array<Object> subtaskTrainDecisionNonAbstractClasses;
    protected DownTime.OrgInfos orgInfos;
    protected ConditionInstance.Docs docs;
    protected ConditionInstance.Rmks rmks;
    protected SubtaskTrainStepDefinition.LevOfLearn levOfLearn;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public TaskTrainDecisionIterationIdentifier getIterationId() {
        return iterationId;
    }

    public void setIterationId(TaskTrainDecisionIterationIdentifier value) {
        this.iterationId = value;
    }

    public Array<TaskTrainDecisionRationale> getDcsnRtnle() {
        if (dcsnRtnle == null) {
            dcsnRtnle = new Array<TaskTrainDecisionRationale>();
        }
        return this.dcsnRtnle;
    }

    public Array<TaskTrainDecisionIterationRationale> getIterRtnle() {
        if (iterRtnle == null) {
            iterRtnle = new Array<TaskTrainDecisionIterationRationale>();
        }
        return this.iterRtnle;
    }

    public TaskTrainDecisionIterationDate getIterDate() {
        return iterDate;
    }

    public void setIterDate(TaskTrainDecisionIterationDate value) {
        this.iterDate = value;
    }

    public TaskTargetAudience getAudience() {
        return audience;
    }

    public void setAudience(TaskTargetAudience value) {
        this.audience = value;
    }

    public TaskHumanInteractionRequirement getCoordCat() {
        return coordCat;
    }

    public void setCoordCat(TaskHumanInteractionRequirement value) {
        this.coordCat = value;
    }

    public TaskDifficultyCategory getTaskDiff() {
        return taskDiff;
    }

    public void setTaskDiff(TaskDifficultyCategory value) {
        this.taskDiff = value;
    }

    public TaskImportanceCategory getTaskImp() {
        return taskImp;
    }

    public void setTaskImp(TaskImportanceCategory value) {
        this.taskImp = value;
    }

    public TaskFrequencyCategory getTaskFreq() {
        return taskFreq;
    }

    public void setTaskFreq(TaskFrequencyCategory value) {
        this.taskFreq = value;
    }

    public TaskTrainLevel getTrainLev() {
        return trainLev;
    }

    public void setTrainLev(TaskTrainLevel value) {
        this.trainLev = value;
    }

    public Array<TaskTrainLevelRationale> getTrainLevRtnle() {
        if (trainLevRtnle == null) {
            trainLevRtnle = new Array<TaskTrainLevelRationale>();
        }
        return this.trainLevRtnle;
    }

    public TaskTrainingDifficulty getTrainDiff() {
        return trainDiff;
    }

    public void setTrainDiff(TaskTrainingDifficulty value) {
        this.trainDiff = value;
    }

    public TaskTrainingDecision getTrainTask() {
        return trainTask;
    }

    public void setTrainTask(TaskTrainingDecision value) {
        this.trainTask = value;
    }

    public Array<TaskTrainingDecisionRationale> getTrainRtnle() {
        if (trainRtnle == null) {
            trainRtnle = new Array<TaskTrainingDecisionRationale>();
        }
        return this.trainRtnle;
    }

    public Array<TaskPerformanceObjective> getPerfObj() {
        if (perfObj == null) {
            perfObj = new Array<TaskPerformanceObjective>();
        }
        return this.perfObj;
    }

    public AlgorithmDerivedTaskTrainLevel getAlgTrainLev() {
        return algTrainLev;
    }

    public void setAlgTrainLev(AlgorithmDerivedTaskTrainLevel value) {
        this.algTrainLev = value;
    }

    public Array<Object> getSubtaskTrainDecisionNonAbstractClasses() {
        if (subtaskTrainDecisionNonAbstractClasses == null) {
            subtaskTrainDecisionNonAbstractClasses = new Array<Object>();
        }
        return this.subtaskTrainDecisionNonAbstractClasses;
    }

    public DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(ConditionInstance.Docs value) {
        this.docs = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public SubtaskTrainStepDefinition.LevOfLearn getLevOfLearn() {
        return levOfLearn;
    }

    public void setLevOfLearn(SubtaskTrainStepDefinition.LevOfLearn value) {
        this.levOfLearn = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public TaskTrainDecisionByEvaluation() {
		super("http://www.asd-europe.org/s-series/s6000t", "TaskTrainDecisionByEvaluation");
	}

}
