/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:55 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;

public class TaskTrainingDecision extends EcRemoteLinkedData {

    protected Boolean value;

    public Boolean isValue() {
        return value;
    }

    public void setValue(Boolean value) {
        this.value = value;
    }

	public TaskTrainingDecision() {
		super("http://www.asd-europe.org/s-series/s6000t", "TaskTrainingDecision");
	}

}
