/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:55 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s3000l.CrudCodeValues;

public class TaskKnowledgeSkillAttitudeGap extends EcRemoteLinkedData {

    protected TaskKnowledgeSkillAttitudeGapIdentifier gapId;
    protected Array<TaskKnowledgeSkillAttitudeGapDescription> gapDescr;
    protected KnowledgeSkillAttitudeLearningObjectiveItem lolLearnObjs;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public TaskKnowledgeSkillAttitudeGapIdentifier getGapId() {
        return gapId;
    }

    public void setGapId(TaskKnowledgeSkillAttitudeGapIdentifier value) {
        this.gapId = value;
    }

    public Array<TaskKnowledgeSkillAttitudeGapDescription> getGapDescr() {
        if (gapDescr == null) {
            gapDescr = new Array<TaskKnowledgeSkillAttitudeGapDescription>();
        }
        return this.gapDescr;
    }

    public KnowledgeSkillAttitudeLearningObjectiveItem getLolLearnObjs() {
        return lolLearnObjs;
    }

    public void setLolLearnObjs(KnowledgeSkillAttitudeLearningObjectiveItem value) {
        this.lolLearnObjs = value;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public TaskKnowledgeSkillAttitudeGap() {
		super("http://www.asd-europe.org/s-series/s6000t", "TaskKnowledgeSkillAttitudeGap");
	}

}
