/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:55 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s3000l.*;

public class TaskKnowledgeSkillAttitudeRequirement extends EcRemoteLinkedData {

    protected TaskKnowledgeSkillAttitudeRequirementIdentifier ksaReqId;
    protected Array<TaskAffectiveLevelOfLearning> affecLoL;
    protected Array<TaskCognitiveLevelOfLearning> cognLoL;
    protected Array<TaskPsychomotorLevelOfLearning> psychLoL;
    protected TradeReference tradeRef;
    protected SkillLevelReference skillLevelRef;
    protected SkillReference skillRef;
    protected JobPositionRef jobPosRef;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public TaskKnowledgeSkillAttitudeRequirementIdentifier getKsaReqId() {
        return ksaReqId;
    }

    public void setKsaReqId(TaskKnowledgeSkillAttitudeRequirementIdentifier value) {
        this.ksaReqId = value;
    }

    public Array<TaskAffectiveLevelOfLearning> getAffecLoL() {
        if (affecLoL == null) {
            affecLoL = new Array<TaskAffectiveLevelOfLearning>();
        }
        return this.affecLoL;
    }

    public Array<TaskCognitiveLevelOfLearning> getCognLoL() {
        if (cognLoL == null) {
            cognLoL = new Array<TaskCognitiveLevelOfLearning>();
        }
        return this.cognLoL;
    }

    public Array<TaskPsychomotorLevelOfLearning> getPsychLoL() {
        if (psychLoL == null) {
            psychLoL = new Array<TaskPsychomotorLevelOfLearning>();
        }
        return this.psychLoL;
    }

    public TradeReference getTradeRef() {
        return tradeRef;
    }

    public void setTradeRef(TradeReference value) {
        this.tradeRef = value;
    }

    public SkillLevelReference getSkillLevelRef() {
        return skillLevelRef;
    }

    public void setSkillLevelRef(SkillLevelReference value) {
        this.skillLevelRef = value;
    }

    public SkillReference getSkillRef() {
        return skillRef;
    }

    public void setSkillRef(SkillReference value) {
        this.skillRef = value;
    }

    public JobPositionRef getJobPosRef() {
        return jobPosRef;
    }

    public void setJobPosRef(JobPositionRef value) {
        this.jobPosRef = value;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public TaskKnowledgeSkillAttitudeRequirement() {
		super("http://www.asd-europe.org/s-series/s6000t", "TaskKnowledgeSkillAttitudeRequirement");
	}

}
