/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:55 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s3000l.*;

public class TaskPsychomotorLevelOfLearning extends EcRemoteLinkedData {

    protected LevelOfLearningIterationIdentifier iterId;
    protected Array<LevelOfLearningKnowledge> knowlLev;
    protected Array<LevelOfLearningRationale> lolRtnle;
    protected Array<LevelOfLearningIterationRationale> iterRtnle;
    protected LevelOfLearningIterationDate iterDate;
    protected PsychomotorLevelOfLearning lol;
    protected Array<TaskKnowledgeSkillAttitudeGapAnalysisRecord> gapRec;
    protected KnowledgeSkillAttitudeLearningObjectiveItem lolLearnObjs;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public LevelOfLearningIterationIdentifier getIterId() {
        return iterId;
    }

    public void setIterId(LevelOfLearningIterationIdentifier value) {
        this.iterId = value;
    }

    public Array<LevelOfLearningKnowledge> getKnowlLev() {
        if (knowlLev == null) {
            knowlLev = new Array<LevelOfLearningKnowledge>();
        }
        return this.knowlLev;
    }

    public Array<LevelOfLearningRationale> getLolRtnle() {
        if (lolRtnle == null) {
            lolRtnle = new Array<LevelOfLearningRationale>();
        }
        return this.lolRtnle;
    }

    public Array<LevelOfLearningIterationRationale> getIterRtnle() {
        if (iterRtnle == null) {
            iterRtnle = new Array<LevelOfLearningIterationRationale>();
        }
        return this.iterRtnle;
    }

    public LevelOfLearningIterationDate getIterDate() {
        return iterDate;
    }

    public void setIterDate(LevelOfLearningIterationDate value) {
        this.iterDate = value;
    }

    public PsychomotorLevelOfLearning getLol() {
        return lol;
    }

    public void setLol(PsychomotorLevelOfLearning value) {
        this.lol = value;
    }

    public Array<TaskKnowledgeSkillAttitudeGapAnalysisRecord> getGapRec() {
        if (gapRec == null) {
            gapRec = new Array<TaskKnowledgeSkillAttitudeGapAnalysisRecord>();
        }
        return this.gapRec;
    }

    public KnowledgeSkillAttitudeLearningObjectiveItem getLolLearnObjs() {
        return lolLearnObjs;
    }

    public void setLolLearnObjs(KnowledgeSkillAttitudeLearningObjectiveItem value) {
        this.lolLearnObjs = value;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public TaskPsychomotorLevelOfLearning() {
		super("http://www.asd-europe.org/s-series/s6000t", "TaskPsychomotorLevelOfLearning");
	}

}
