/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:03 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s3000l.CrudCodeValues;

public class TaskKnowledgeSkillAttitudeGap extends EcRemoteLinkedData {

    protected TaskKnowledgeSkillAttitudeGapIdentifier taskKSAGapId;
    protected Array<TaskKnowledgeSkillAttitudeGapDescription> taskKSAGapDescr;
    protected PrerequisiteCompetenciesDefinitionRef evalCompDef;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public TaskKnowledgeSkillAttitudeGapIdentifier getTaskKSAGapId() {
        return taskKSAGapId;
    }

    public void setTaskKSAGapId(TaskKnowledgeSkillAttitudeGapIdentifier value) {
        this.taskKSAGapId = value;
    }

    public Array<TaskKnowledgeSkillAttitudeGapDescription> getTaskKSAGapDescr() {
        if (taskKSAGapDescr == null) {
            taskKSAGapDescr = new Array<TaskKnowledgeSkillAttitudeGapDescription>();
        }
        return this.taskKSAGapDescr;
    }

    public PrerequisiteCompetenciesDefinitionRef getEvalCompDef() {
        return evalCompDef;
    }

    public void setEvalCompDef(PrerequisiteCompetenciesDefinitionRef value) {
        this.evalCompDef = value;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public TaskKnowledgeSkillAttitudeGap() {
		super("http://www.asd-europe.org/s-series/s3000l", "TaskKnowledgeSkillAttitudeGap");
	}

}
