/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:03 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;

public class TrainingPopulationCharacteristics extends EcRemoteLinkedData {

    protected Array<TrainingPopulationDescription> trainPopDescr;
    protected Array<TrainingPopulationNumberOfPeople> number;

    public Array<TrainingPopulationDescription> getTrainPopDescr() {
        if (trainPopDescr == null) {
            trainPopDescr = new Array<TrainingPopulationDescription>();
        }
        return this.trainPopDescr;
    }

    public Array<TrainingPopulationNumberOfPeople> getNumber() {
        if (number == null) {
            number = new Array<TrainingPopulationNumberOfPeople>();
        }
        return this.number;
    }

	public TrainingPopulationCharacteristics() {
		super("http://www.asd-europe.org/s-series/s3000l", "TrainingPopulationCharacteristics");
	}

}
