/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Sep 12 10:06:03 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import s3000l.*;

public class TrainingComponentSpecialResourceRequirementReference extends EcRemoteLinkedData {

    protected TrainingComponentSpecialResourceRequirementReferenceType refType;
    protected ProductReference prodRef;
    protected ProductVariantReference prodVarRef;
    protected PartAsDesignedReference partRef;
    protected BreakdownElementReference beRef;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public TrainingComponentSpecialResourceRequirementReferenceType getRefType() {
        return refType;
    }

    public void setRefType(TrainingComponentSpecialResourceRequirementReferenceType value) {
        this.refType = value;
    }

    public ProductReference getProdRef() {
        return prodRef;
    }

    public void setProdRef(ProductReference value) {
        this.prodRef = value;
    }

    public ProductVariantReference getProdVarRef() {
        return prodVarRef;
    }

    public void setProdVarRef(ProductVariantReference value) {
        this.prodVarRef = value;
    }

    public PartAsDesignedReference getPartRef() {
        return partRef;
    }

    public void setPartRef(PartAsDesignedReference value) {
        this.partRef = value;
    }

    public BreakdownElementReference getBeRef() {
        return beRef;
    }

    public void setBeRef(BreakdownElementReference value) {
        this.beRef = value;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public TrainingComponentSpecialResourceRequirementReference() {
		super("http://www.asd-europe.org/s-series/s3000l", "TrainingComponentSpecialResourceRequirementReference");
	}

}
