/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Thu Aug 22 12:47:55 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s3000l.*;

public class WarningCautionTrainDecision extends EcRemoteLinkedData {

    protected WarningCautionTrainDecisionIterationIdentifier iterationId;
    protected WarningCautionTrainingLevel trainLev;
    protected Array<WarningCautionTrainingLevelRationale> trainLevRtnle;
    protected Array<WarningCautionTrainDecisionIterationRationale> iterRtnle;
    protected WarningCautionTrainDecisionIterationDate iterDate;
    protected s3000l.DownTime.OrgInfos orgInfos;
    protected s3000l.ConditionInstance.Docs docs;
    protected s3000l.ConditionInstance.Rmks rmks;
    protected Array<TaskKnowledgeSkillAttitudeRequirementItem> ksaReqs;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public WarningCautionTrainDecisionIterationIdentifier getIterationId() {
        return iterationId;
    }

    public void setIterationId(WarningCautionTrainDecisionIterationIdentifier value) {
        this.iterationId = value;
    }

    public WarningCautionTrainingLevel getTrainLev() {
        return trainLev;
    }

    public void setTrainLev(WarningCautionTrainingLevel value) {
        this.trainLev = value;
    }

    public Array<WarningCautionTrainingLevelRationale> getTrainLevRtnle() {
        if (trainLevRtnle == null) {
            trainLevRtnle = new Array<WarningCautionTrainingLevelRationale>();
        }
        return this.trainLevRtnle;
    }

    public Array<WarningCautionTrainDecisionIterationRationale> getIterRtnle() {
        if (iterRtnle == null) {
            iterRtnle = new Array<WarningCautionTrainDecisionIterationRationale>();
        }
        return this.iterRtnle;
    }

    public WarningCautionTrainDecisionIterationDate getIterDate() {
        return iterDate;
    }

    public void setIterDate(WarningCautionTrainDecisionIterationDate value) {
        this.iterDate = value;
    }

    public s3000l.DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(s3000l.DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public s3000l.ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(s3000l.ConditionInstance.Docs value) {
        this.docs = value;
    }

    public s3000l.ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(s3000l.ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public Array<TaskKnowledgeSkillAttitudeRequirementItem> getKsaReqs() {
        if (ksaReqs == null) {
            ksaReqs = new Array<TaskKnowledgeSkillAttitudeRequirementItem>();
        }
        return this.ksaReqs;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public WarningCautionTrainDecision() {
		super("http://www.asd-europe.org/s-series/s6000t", "WarningCautionTrainDecision");
	}

}
