/**
 *
 * Generated by JaxbToStjsAssimilater.
 * Assimilation Date: Mon Jul 29 11:33:23 CDT 2019
 *
 **/

package s6000t;

import org.cassproject.schema.general.EcRemoteLinkedData;
import org.stjs.javascript.Array;
import s3000l.*;

public class WarningCautionTrainDecision extends EcRemoteLinkedData {

    protected WarningCautionTrainDecisionIterationIdentifier iterationId;
    protected WarningCautionTrainLevel trainLev;
    protected Array<WarningCautionTrainLevelRationale> trainLevRtnle;
    protected Array<WarningCautionTrainDecisionIterationRationale> iterRtnle;
    protected WarningCautionTrainDecisionIterationDate iterDate;
    protected DownTime.OrgInfos orgInfos;
    protected ConditionInstance.Docs docs;
    protected ConditionInstance.Rmks rmks;
    protected SubtaskTrainStepDefinition.LevOfLearn levOfLearn;
    protected String uid;
    protected String uri;
    protected CrudCodeValues crud;

    public WarningCautionTrainDecisionIterationIdentifier getIterationId() {
        return iterationId;
    }

    public void setIterationId(WarningCautionTrainDecisionIterationIdentifier value) {
        this.iterationId = value;
    }

    public WarningCautionTrainLevel getTrainLev() {
        return trainLev;
    }

    public void setTrainLev(WarningCautionTrainLevel value) {
        this.trainLev = value;
    }

    public Array<WarningCautionTrainLevelRationale> getTrainLevRtnle() {
        if (trainLevRtnle == null) {
            trainLevRtnle = new Array<WarningCautionTrainLevelRationale>();
        }
        return this.trainLevRtnle;
    }

    public Array<WarningCautionTrainDecisionIterationRationale> getIterRtnle() {
        if (iterRtnle == null) {
            iterRtnle = new Array<WarningCautionTrainDecisionIterationRationale>();
        }
        return this.iterRtnle;
    }

    public WarningCautionTrainDecisionIterationDate getIterDate() {
        return iterDate;
    }

    public void setIterDate(WarningCautionTrainDecisionIterationDate value) {
        this.iterDate = value;
    }

    public DownTime.OrgInfos getOrgInfos() {
        return orgInfos;
    }

    public void setOrgInfos(DownTime.OrgInfos value) {
        this.orgInfos = value;
    }

    public ConditionInstance.Docs getDocs() {
        return docs;
    }

    public void setDocs(ConditionInstance.Docs value) {
        this.docs = value;
    }

    public ConditionInstance.Rmks getRmks() {
        return rmks;
    }

    public void setRmks(ConditionInstance.Rmks value) {
        this.rmks = value;
    }

    public SubtaskTrainStepDefinition.LevOfLearn getLevOfLearn() {
        return levOfLearn;
    }

    public void setLevOfLearn(SubtaskTrainStepDefinition.LevOfLearn value) {
        this.levOfLearn = value;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String value) {
        this.uid = value;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String value) {
        this.uri = value;
    }

    public CrudCodeValues getCrud() {
        if (crud == null) {
            return CrudCodeValues.I;
        } else {
            return crud;
        }
    }

    public void setCrud(CrudCodeValues value) {
        this.crud = value;
    }

	public WarningCautionTrainDecision() {
		super("http://www.asd-europe.org/s-series/s6000t", "WarningCautionTrainDecision");
	}

}
